(()=>{
const API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-assistant';
const DEMO_ITEMS=[
 {id:'demo-wa-1',channel:'whatsapp',sender_name:'נועה כהן',sender_address:'050-0000000',patient_name:'לולה',received_at:new Date(Date.now()-12*60000).toISOString(),subject:'שאלה אחרי טיפול',body_text:'היי, לולה עברה היום ניקוי שיניים והיא עדיין קצת ישנונית. זה תקין?',preview:'לולה עדיין ישנונית אחרי ניקוי שיניים',category:'אחרי טיפול',priority:'high',status:'needs_attention',metadata:{ai_summary:'לולה עברה היום ניקוי שיניים והבעלים מדווחת על ישנוניות. נדרשת בדיקת איש צוות לפני מתן מענה.',draft_reply:'היי נועה, תודה שעדכנת אותנו. ישנוניות מסוימת יכולה להופיע לאחר טשטוש, אבל כדי לוודא שהכול תקין נבקש לדעת אם לולה ערנית כשקוראים לה, נושמת כרגיל ומצליחה לעמוד. אם יש קושי בנשימה, חוסר תגובה או החמרה — יש ליצור איתנו קשר טלפוני מיד.',assigned_to:'רופא/ה'}},
 {id:'demo-mail-1',channel:'gmail',sender_name:'מעבדת AML',sender_address:'results@example.test',received_at:new Date(Date.now()-48*60000).toISOString(),subject:'תוצאות בדיקה – מיקה',body_text:'מצורפות תוצאות בדיקות המעבדה עבור מיקה, מספר הפניה 4581.',preview:'התקבלו תוצאות מעבדה עבור מיקה',category:'תוצאות מעבדה',priority:'normal',status:'new',metadata:{ai_summary:'התקבל מייל עם תוצאות מעבדה עבור מיקה. יש לשייך לתיק המטופלת ולהעביר לרופא/ה.',draft_reply:'תודה, התוצאות התקבלו והועברו לצוות הרפואי לבדיקה.',assigned_to:'רופא/ה'}},
 {id:'demo-wa-2',channel:'whatsapp',sender_name:'איתי לוי',sender_address:'052-0000000',patient_name:'צ׳ארלי',received_at:new Date(Date.now()-95*60000).toISOString(),subject:'בקשה לקביעת תור',body_text:'אפשר לקבוע לצ׳ארלי חיסון משושה ביום חמישי אחר הצהריים?',preview:'מבקש תור לחיסון משושה ביום חמישי',category:'קביעת תור',priority:'normal',status:'new',metadata:{ai_summary:'בקשה לקביעת תור לחיסון משושה ביום חמישי אחר הצהריים.',draft_reply:'היי איתי, בשמחה. נבדוק את התורים הפנויים ביום חמישי אחר הצהריים ונחזור אליך עם שעה מתאימה.',assigned_to:'קבלה'}}
];
let reminders=[],inbox=[],connections={gmail:false,whatsapp:false},gmailDetails={},installPrompt=null,dataLoaded=false,dataLoading=null,filter='all',categoryFilter='all',selectedId=null,demoMode=false;
const displayText=s=>{let text=String(s??'');const named={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:'\u00a0',ndash:'\u2013',mdash:'\u2014',lsquo:'\u2018',rsquo:'\u2019',ldquo:'\u201c',rdquo:'\u201d',hellip:'\u2026',bull:'\u2022',middot:'\u00b7',lrm:'\u200e',rlm:'\u200f',zwnj:'\u200c',zwj:'\u200d'};for(let pass=0;pass<3;pass++){const next=text.replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos|nbsp|ndash|mdash|lsquo|rsquo|ldquo|rdquo|hellip|bull|middot|lrm|rlm|zwnj|zwj);/gi,(match,entity)=>{const key=entity.toLowerCase();if(key[0]!=='#')return named[key]??match;const code=key[1]==='x'?Number.parseInt(key.slice(2),16):Number.parseInt(key.slice(1),10);if(!Number.isFinite(code)||code<0||code>0x10ffff||(code>=0xd800&&code<=0xdfff))return match;if(code===0x200b)return '';try{return String.fromCodePoint(code)}catch{return match}});if(next===text)break;text=next}return text};
const esc=s=>displayText(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const meta=x=>x&&typeof x.metadata==='object'&&x.metadata?x.metadata:{};
const channelLabel=x=>x==='gmail'?'מייל':x==='whatsapp'?'ווטסאפ':'ידני';
const priorityLabel=x=>({urgent:'דחוף',high:'חשוב',normal:'רגיל',low:'נמוך'}[x]||'רגיל');
const statusLabel=x=>({new:'חדש',needs_attention:'דורש טיפול',waiting:'ממתין',done:'טופל',archived:'בארכיון'}[x]||'חדש');
const topicClass=x=>({'תוצאות בדיקות':'results','תוצאות מעבדה':'results','פניות רפואיות':'medical','אחרי טיפול':'medical','תורים וקבלה':'appointments','קביעת תור':'appointments','חשבוניות ותשלומים':'billing','ספקים והזמנות':'suppliers','מערכות ופרסום':'systems','כללי':'general'}[x]||'general');
async function api(body){if(window.ClinicData)return ClinicData.request('assistant',body);const token=localStorage.getItem('clinic_session_token')||'';if(!token)throw new Error('נדרשת התחברות');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function addCss(){if(document.querySelector('link[data-assistant-center]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='assistant-center.css?v=8';l.dataset.assistantCenter='1';document.head.appendChild(l)}
function addPwa(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.webmanifest?v=1';document.head.appendChild(l)}if('serviceWorker'in navigator)navigator.serviceWorker.register('clinic-sw.js?v=1').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e})}
function inject(){if(document.getElementById('assistant'))return;const app=document.getElementById('app');if(!app)return;const sec=document.createElement('section');sec.id='assistant';sec.className='panel hidden';sec.innerHTML=`
 <div class="assistant-head"><div><h2>עוזר המרפאה</h2><p>כאן רואים פניות שהגיעו למייל, בודקים אותן ושומרים טיוטה לצוות.</p></div><div class="assistant-head-actions"><button class="btn" onclick="assistantToggleDemo()" id="assistantDemoBtn">פתיחת הדגמה</button></div></div>
 <section class="assistant-howto" aria-label="איך משתמשים בעוזר המרפאה"><div class="assistant-howto-title"><b>איך זה עובד?</b><span>שלושה צעדים פשוטים</span></div><div class="assistant-steps"><article><i>1</i><div><b>מחברים את המייל</b><small>החיבור מאפשר קריאה בלבד</small></div></article><article><i>2</i><div><b>מסנכרנים הודעות</b><small>לחצי על „סנכרון עכשיו” כדי לטעון מיילים</small></div></article><article><i>3</i><div><b>בודקים ומטפלים</b><small>פותחים פנייה, עורכים טיוטה ומעבירים לצוות</small></div></article></div></section>
 <div class="assistant-grid"><article class="assistant-status gmail"><span class="assistant-status-icon">✉️</span><div class="assistant-status-content"><small>מייל המרפאה</small><b id="assistantGmailTitle">עדיין לא מחובר</b><em id="assistantGmailState">ממתין לחיבור Google</em><div class="assistant-connect-actions"><button id="assistantGmailConnectBtn" class="btn" onclick="assistantConnectGmail()">חיבור Gmail</button><button id="assistantGmailSyncBtn" class="btn hidden" onclick="assistantSyncGmail()">סנכרון עכשיו</button></div></div></article><article class="assistant-status whatsapp"><span class="assistant-status-icon">💬</span><div><small>ווטסאפ המרפאה</small><b id="assistantWhatsappTitle">עדיין לא מחובר</b><em id="assistantWhatsappState">ממתין למספר ניסיון</em></div></article><article class="assistant-status notify"><span class="assistant-status-icon">🔔</span><div><small>התראות במחשב</small><b id="assistantNotificationTitle">בודק הרשאה...</b><em id="assistantNotificationState">—</em><button class="btn" onclick="assistantEnableNotifications()">הפעלת התראות</button></div></article></div>
 <div id="assistantDemoBanner" class="assistant-demo-banner hidden"><b>מצב הדגמה בלבד</b><span>אלה הודעות לדוגמה. לא נשלח דבר ללקוחות ולא נשמר מידע אמיתי.</span></div>
 <div class="assistant-kpis"><article><div><small>פניות פתוחות</small><span>כל ההודעות שעדיין לא טופלו</span></div><b id="assistantNeedsCount">0</b></article><article><div><small>מיילים</small><span>הודעות שסונכרנו מ־Gmail</span></div><b id="assistantMailCount">0</b></article><article><div><small>נושאים</small><span>קטגוריות שמופיעות כרגע</span></div><b id="assistantTopicCount">0</b></article></div>
 <div class="assistant-inbox-layout"><section class="assistant-card assistant-list-card"><div class="assistant-card-head"><div><h3>הודעות נכנסות</h3><small>בחרי הודעה כדי לראות את הסיכום</small></div><span id="assistantInboxCount" class="assistant-mini-count">0</span></div><div class="assistant-filter-label">סינון הודעות:</div><div class="assistant-filter-row"><button class="active" onclick="assistantSetFilter('all',this)">הכול</button><button onclick="assistantSetFilter('gmail',this)">מייל</button><button onclick="assistantSetFilter('whatsapp',this)">ווטסאפ</button></div><label class="assistant-category-filter"><span>לפי נושא</span><select id="assistantCategoryFilter" onchange="assistantSetCategoryFilter(this.value)"><option value="all">כל הנושאים</option></select></label><div id="assistantInbox" class="assistant-inbox-list"></div></section><section id="assistantConversation" class="assistant-card assistant-conversation"><div class="assistant-card-head"><div><h3>סיכום הפנייה</h3><small>בחרי הודעה מהרשימה כדי לפתוח אותה</small></div></div><div class="assistant-empty"><b>עדיין לא נבחרה הודעה</b>כשתבחרי הודעה, יוצגו כאן הנושא, הסיכום והטיוטה.</div></section></div>
 <div id="whatsappDemoRoot"></div>
 <details class="assistant-card assistant-reminders-wrap"><summary>תזכורות פנימיות לצוות <span id="assistantReminderCount" class="assistant-mini-count">0</span></summary><div class="assistant-body"><div class="assistant-reminder-form"><input id="assistantReminderTitle" placeholder="למשל: להתקשר לבעלים של לולה"><input id="assistantReminderAt" type="datetime-local"><textarea id="assistantReminderNotes" placeholder="הערה אופציונלית"></textarea><div class="assistant-reminder-actions"><small>התזכורת משותפת לכל מחשבי המרפאה.</small><button class="btn primary" onclick="assistantSaveReminder()">+ שמירה</button></div></div><div id="assistantReminders" class="assistant-reminders"></div></div></details>`;const anchor=document.getElementById('simulation')||document.getElementById('prices');if(anchor)anchor.insertAdjacentElement('afterend',sec);else app.appendChild(sec);updateNotificationState()}
function fmtDate(v){try{return new Date(v).toLocaleString('he-IL',{dateStyle:'short',timeStyle:'short'})}catch{return v}}
function visibleItems(){return inbox.filter(x=>!['done','archived'].includes(x.status)&&(filter==='all'||x.channel===filter)&&(categoryFilter==='all'||(x.category||'כללי')===categoryFilter)).sort((a,b)=>(a.category||'כללי').localeCompare(b.category||'כללי','he')||new Date(b.received_at)-new Date(a.received_at))}
function renderStats(){const open=inbox.filter(x=>!['done','archived'].includes(x.status)),topics=new Set(open.map(x=>x.category||'כללי'));document.getElementById('assistantInboxCount').textContent=String(open.length);document.getElementById('assistantNeedsCount').textContent=String(open.length);document.getElementById('assistantMailCount').textContent=String(open.filter(x=>x.channel==='gmail').length);document.getElementById('assistantTopicCount').textContent=String(topics.size)}
function renderCategoryFilter(){const el=document.getElementById('assistantCategoryFilter');if(!el)return;const categories=[...new Set(inbox.filter(x=>!['done','archived'].includes(x.status)).map(x=>x.category||'כללי'))].sort((a,b)=>a.localeCompare(b,'he'));if(categoryFilter!=='all'&&!categories.includes(categoryFilter))categoryFilter='all';el.innerHTML='<option value="all">כל הנושאים</option>'+categories.map(x=>`<option value="${esc(x)}" ${categoryFilter===x?'selected':''}>${esc(x)}</option>`).join('')}
function renderInbox(){const box=document.getElementById('assistantInbox');if(!box)return;renderStats();renderCategoryFilter();const rows=visibleItems();if(!rows.length){const title=connections.gmail?'אין הודעות בנושא הזה':'המייל עדיין לא מחובר';const msg=connections.gmail?'נסי לבחור „כל הנושאים” או לחצי על „סנכרון עכשיו” כדי לבדוק אם הגיעו הודעות חדשות.':'לחצי על „חיבור Gmail” למעלה כדי להתחיל.';box.innerHTML=`<div class="assistant-empty"><b>${title}</b>${msg}</div>`;renderConversation();return}if(!rows.some(x=>String(x.id)===String(selectedId)))selectedId=rows[0].id;let lastCategory='';box.innerHTML=rows.map(x=>{const category=x.category||'כללי',topic=topicClass(category),heading=category!==lastCategory?`<div class="assistant-group-heading topic-${topic}">${esc(category)}</div>`:'';lastCategory=category;const m=meta(x),active=String(x.id)===String(selectedId);return `${heading}<button class="assistant-inbox-item ${esc(x.channel||'manual')} topic-${topic} ${active?'selected':''}" onclick="assistantSelect('${esc(x.id)}')"><div class="assistant-inbox-top"><span class="assistant-channel">${channelLabel(x.channel)}</span><small>${fmtDate(x.received_at)}</small></div><div class="assistant-inbox-title"><h4>${esc(x.sender_name||x.sender_address||'פנייה חדשה')}</h4><span class="assistant-category-tag topic-${topic}">${esc(category)}</span></div><b class="assistant-subject" dir="auto">${esc(x.subject||'ללא נושא')}</b><p>${esc(m.ai_summary||x.preview||'')}</p><footer><span>${statusLabel(x.status)}</span>${m.draft_reply?'<span>טיוטה מוכנה</span>':''}${x.patient_name?`<span>מטופל/ת: ${esc(x.patient_name)}</span>`:''}</footer></button>`}).join('');renderConversation()}
function renderConversation(){const box=document.getElementById('assistantConversation');if(!box)return;const x=inbox.find(i=>String(i.id)===String(selectedId));if(!x){box.innerHTML='<div class="assistant-card-head"><div><h3>סיכום הפנייה</h3><small>בחרי הודעה מהרשימה כדי לפתוח אותה</small></div></div><div class="assistant-empty"><b>עדיין לא נבחרה הודעה</b>כשתבחרי הודעה, יוצגו כאן הנושא, הסיכום והטיוטה.</div>';return}const m=meta(x),topic=topicClass(x.category||'כללי');box.innerHTML=`<div class="assistant-conversation-head"><div><span class="assistant-channel">${channelLabel(x.channel)}</span><span class="assistant-category-tag topic-${topic}">${esc(x.category||'כללי')}</span><h3>${esc(x.sender_name||x.sender_address||'פנייה חדשה')}</h3><p>${esc(x.sender_address||'')}${x.patient_name?` · ${esc(x.patient_name)}`:''}</p><p class="assistant-subject-line"><b>נושא:</b> <bdi dir="auto">${esc(x.subject||'ללא נושא')}</bdi> · ${fmtDate(x.received_at)}</p></div></div><div class="assistant-summary-block"><small>סיכום קצר · ללא Gemini</small><p>${esc(m.ai_summary||'לא זמין סיכום למייל הזה. אפשר לקרוא את ההודעה המלאה למטה.')}</p></div><details class="assistant-original-email"><summary>הצגת המייל המקורי המלא</summary><div><p dir="auto">${esc(x.body_text||x.preview||'אין תוכן טקסטואלי במייל. ייתכן שיש קובץ מצורף.')}</p></div></details><label class="assistant-draft"><span>טיוטת תשובה <small>ערכי את הנוסח ולחצי „שמירת טיוטה”</small></span><textarea id="assistantDraft">${esc(m.draft_reply||'')}</textarea></label><div class="assistant-assignment"><label for="assistantAssignee">אחראי/ת לטיפול:</label><select id="assistantAssignee"><option ${m.assigned_to==='קבלה'?'selected':''}>קבלה</option><option ${m.assigned_to==='אסיסטנט/ית'?'selected':''}>אסיסטנט/ית</option><option ${m.assigned_to==='רופא/ה'?'selected':''}>רופא/ה</option></select></div><div class="assistant-conversation-actions"><button class="btn primary" onclick="assistantSaveDraft()">שמירת טיוטה</button><button class="btn" onclick="assistantEscalate()">העברה לרופא/ה</button><button class="btn" onclick="assistantMarkDone()">סימון כטופל</button></div><div class="assistant-safety-note"><b>שימי לב:</b> החיבור לג׳ימייל הוא לקריאה בלבד. אפשר לשמור טיוטה ולעדכן את הצוות, אך שליחה ישירות מהממשק אינה זמינה כרגע.</div>`}
function updateLocal(id,patch){const i=inbox.findIndex(x=>String(x.id)===String(id));if(i<0)return;const current=inbox[i];inbox[i]={...current,...patch,metadata:{...meta(current),...(patch.metadata||{})}}}
async function persist(patch){const id=selectedId;if(!id)return;if(demoMode){updateLocal(id,patch);renderInbox();return}const j=await api({action:'inbox_update',id,...patch});if(j.item){const i=inbox.findIndex(x=>String(x.id)===String(id));if(i>=0)inbox[i]=j.item;ClinicData?.localInbox?.(j.item)}renderInbox()}
window.assistantSetFilter=(next,button)=>{filter=next;document.querySelectorAll('.assistant-filter-row button').forEach(b=>b.classList.toggle('active',b===button));renderInbox()};window.assistantSetCategoryFilter=next=>{categoryFilter=next;renderInbox()};window.assistantSelect=id=>{selectedId=id;renderInbox()};
window.assistantChangePriority=async value=>{try{await persist({priority:value})}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};
window.assistantSaveDraft=async()=>{const draft=document.getElementById('assistantDraft')?.value.trim()||'',assigned_to=document.getElementById('assistantAssignee')?.value||'קבלה';try{await persist({metadata:{draft_reply:draft,assigned_to}});alert(demoMode?'הטיוטה נשמרה בתוך ההדגמה בלבד':'הטיוטה נשמרה')}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};
window.assistantEscalate=async()=>{const draft=document.getElementById('assistantDraft')?.value.trim()||'';try{await persist({status:'needs_attention',priority:'high',metadata:{draft_reply:draft,assigned_to:'רופא/ה'}})}catch(e){alert('לא הצלחתי להעביר: '+e.message)}};window.assistantMarkDone=async()=>{try{await persist({status:'done'});selectedId=null;renderInbox()}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};
window.assistantSend=()=>{const x=inbox.find(i=>String(i.id)===String(selectedId));if(!x||!connections[x.channel])return alert('החשבון עדיין לא מחובר. בשלב ההדגמה שום דבר לא נשלח ללקוח.');alert('פעולת השליחה תחובר רק לאחר בדיקה עם חשבון הניסיון.')};
window.assistantToggleDemo=()=>{demoMode=!demoMode;document.getElementById('assistantDemoBanner')?.classList.toggle('hidden',!demoMode);const btn=document.getElementById('assistantDemoBtn');if(btn)btn.textContent=demoMode?'סגירת ההדגמה':'פתיחת הדגמה';if(demoMode){inbox=DEMO_ITEMS.map(x=>({...x,metadata:{...x.metadata}}));selectedId=inbox[0].id}else{inbox=[];selectedId=null;dataLoaded=false;load()}renderInbox()};
function renderConnections(){for(const [kind,label] of [['gmail','Gmail'],['whatsapp','Whatsapp']]){const on=!!connections[kind],title=document.getElementById(`assistant${label}Title`),state=document.getElementById(`assistant${label}State`);if(title)title.textContent=on?(kind==='gmail'?(gmailDetails.account_address||'Gmail מחובר'):'מחובר ופועל'):'עדיין לא מחובר';if(state){state.textContent=on?(kind==='gmail'&&gmailDetails.last_synced_at?'סונכרן '+fmtDate(gmailDetails.last_synced_at):'מחובר ומוכן'):'ממתין לחיבור';state.classList.toggle('connected',on)}}const connect=document.getElementById('assistantGmailConnectBtn'),sync=document.getElementById('assistantGmailSyncBtn');if(connect){connect.textContent=connections.gmail?'חיבור מחדש':'חיבור Gmail';connect.disabled=false}sync?.classList.toggle('hidden',!connections.gmail)}
window.assistantConnectGmail=async()=>{const btn=document.getElementById('assistantGmailConnectBtn');if(btn){btn.disabled=true;btn.textContent='פותח את Google...'}try{const j=await ClinicData.request('gmail',{action:'connect_url'});if(!j.url)throw new Error('לא התקבלה כתובת חיבור');location.assign(j.url)}catch(e){if(btn){btn.disabled=false;btn.textContent=connections.gmail?'חיבור מחדש':'חיבור Gmail'}alert('לא הצלחתי לפתוח את החיבור: '+e.message)}};
window.assistantSyncGmail=async()=>{const btn=document.getElementById('assistantGmailSyncBtn');if(btn){btn.disabled=true;btn.textContent='מסנכרן...'}try{const j=await ClinicData.request('gmail',{action:'sync'});ClinicData.clearCache('inbox');dataLoaded=false;await load();alert(`הסנכרון הסתיים. נוספו או עודכנו ${Number(j.imported||0)} הודעות.`)}catch(e){alert('לא הצלחתי לסנכרן: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent='סנכרון עכשיו'}}};
function renderReminders(){const box=document.getElementById('assistantReminders');if(!box)return;const now=Date.now(),open=reminders.filter(x=>!x.done),done=reminders.filter(x=>x.done).slice(-5);document.getElementById('assistantReminderCount').textContent=String(open.length);const rows=[...open,...done];box.innerHTML=rows.length?rows.map(x=>{const due=!x.done&&new Date(x.remind_at).getTime()<=now;return `<div class="assistant-reminder ${due?'due':''} ${x.done?'done':''}"><div><div class="assistant-reminder-title">${esc(x.title)}</div><div class="assistant-reminder-meta">${fmtDate(x.remind_at)}</div>${x.notes?`<div class="assistant-reminder-note">${esc(x.notes)}</div>`:''}</div><div class="assistant-reminder-buttons">${x.done?`<button onclick="assistantReminderDone(${x.id},false)">החזרה</button>`:`<button class="done" onclick="assistantReminderDone(${x.id},true)">✓ בוצע</button><button class="snooze" onclick="assistantSnooze(${x.id},10)">דחי 10 דק׳</button>`}<button class="delete" onclick="assistantDeleteReminder(${x.id})">מחיקה</button></div></div>`}).join(''):'<div class="assistant-empty"><b>אין תזכורות כרגע</b></div>';checkDueNotifications()}
async function load(){if(dataLoaded||demoMode)return;if(dataLoading)return dataLoading;dataLoading=(async()=>{try{const [j,c,g]=await Promise.all([window.ClinicData?ClinicData.assistant():api({action:'bootstrap'}),api({action:'connection_status'}).catch(()=>({})),ClinicData.request('gmail',{action:'status'}).catch(()=>({}))]);reminders=j.reminders||[];inbox=j.inbox||[];gmailDetails=g||{};connections={gmail:!!g.connected,whatsapp:!!c.whatsapp};dataLoaded=true;renderReminders();renderConnections();renderInbox()}catch(e){console.warn(e);const box=document.getElementById('assistantInbox');if(box)box.innerHTML='<div class="assistant-empty">לא הצלחתי לטעון כרגע</div>'}finally{dataLoading=null}})();return dataLoading}
function upsertReminder(item){if(!item)return;const i=reminders.findIndex(x=>Number(x.id)===Number(item.id));if(i>=0)reminders[i]=item;else reminders.unshift(item);ClinicData?.localReminder?.(item);dataLoaded=true;renderReminders()}
window.assistantSaveReminder=async()=>{const title=document.getElementById('assistantReminderTitle')?.value.trim(),at=document.getElementById('assistantReminderAt')?.value,notes=document.getElementById('assistantReminderNotes')?.value.trim();if(!title)return alert('צריך לכתוב מה להזכיר');if(!at)return alert('צריך לבחור תאריך ושעה');try{const j=await api({action:'reminder_save',item:{title,remind_at:new Date(at).toISOString(),notes,created_by:'צוות המרפאה'}});document.getElementById('assistantReminderTitle').value='';document.getElementById('assistantReminderAt').value='';document.getElementById('assistantReminderNotes').value='';upsertReminder(j.item)}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};window.assistantReminderDone=async(id,done)=>{try{const j=await api({action:'reminder_done',id,done});upsertReminder(j.item)}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};window.assistantSnooze=async(id,minutes)=>{try{const j=await api({action:'reminder_snooze',id,minutes});clearNotified(id);upsertReminder(j.item)}catch(e){alert('לא הצלחתי לדחות: '+e.message)}};window.assistantDeleteReminder=async id=>{if(!confirm('למחוק את התזכורת?'))return;try{await api({action:'reminder_delete',id});reminders=reminders.filter(x=>Number(x.id)!==Number(id));ClinicData?.removeReminder?.(id);clearNotified(id);renderReminders()}catch(e){alert('לא הצלחתי למחוק: '+e.message)}};
function getNotified(){try{return new Set(JSON.parse(localStorage.getItem('clinic_assistant_notified')||'[]'))}catch{return new Set()}}function saveNotified(s){localStorage.setItem('clinic_assistant_notified',JSON.stringify([...s].slice(-300)))}function clearNotified(id){const s=getNotified();[...s].filter(k=>String(k).startsWith(id+'|')).forEach(k=>s.delete(k));saveNotified(s)}async function notify(title,body){if(!('Notification'in window)||Notification.permission!=='granted')return false;try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'clinic-app-icon.svg',badge:'clinic-app-icon.svg',tag:'clinic-assistant'});return true}new Notification(title,{body});return true}catch{return false}}function checkDueNotifications(){if(!dataLoaded||document.visibilityState==='hidden'||Notification.permission!=='granted')return;const s=getNotified(),now=Date.now();let changed=false;reminders.filter(x=>!x.done&&new Date(x.remind_at).getTime()<=now).forEach(x=>{const k=`${x.id}|${x.remind_at}`;if(s.has(k))return;s.add(k);changed=true;notify('🐾 תזכורת מהמרפאה',x.title+(x.notes?' — '+x.notes:''))});if(changed)saveNotified(s)}
function updateNotificationState(){const title=document.getElementById('assistantNotificationTitle'),state=document.getElementById('assistantNotificationState');if(!title||!state)return;if(!('Notification'in window)){title.textContent='לא נתמך בדפדפן הזה';state.textContent='לא זמין';return}const p=Notification.permission;if(p==='granted'){title.textContent='התראות פעילות';state.textContent='מוכן';state.classList.add('connected')}else if(p==='denied'){title.textContent='ההתראות חסומות';state.textContent='צריך לאשר בהגדרות'}else{title.textContent='אפשר להפעיל';state.textContent='לא אושר עדיין'}}window.assistantEnableNotifications=async()=>{if(!('Notification'in window))return alert('הדפדפן הזה לא תומך בהתראות');const p=await Notification.requestPermission();updateNotificationState();if(p==='granted')notify('עוזר המרפאה פעיל','מכאן נוכל להקפיץ תזכורות במחשב.')};
function maybeLoad(){const sec=document.getElementById('assistant');if(sec&&!sec.classList.contains('hidden'))load()}function boot(){addCss();addPwa();inject();const core=document.createElement('script');core.src='whatsapp-bot-core.js?v=1';core.onload=()=>{const ui=document.createElement('script');ui.src='whatsapp-simulator-ui.js?v=1';document.body.appendChild(ui)};document.body.appendChild(core);const params=new URLSearchParams(location.search);if(params.get('gmail')==='connected'){history.replaceState({},'',location.pathname+location.hash);setTimeout(()=>alert('Gmail חובר בהצלחה. אפשר ללחוץ עכשיו על “סנכרון עכשיו”.'),250)}else if(params.get('gmail')==='error'){history.replaceState({},'',location.pathname+location.hash);setTimeout(()=>alert('החיבור ל-Gmail לא הושלם. אפשר לנסות שוב מכפתור החיבור.'),250)}const observer=new MutationObserver(maybeLoad),sec=document.getElementById('assistant');if(sec)observer.observe(sec,{attributes:true,attributeFilter:['class']});maybeLoad();setInterval(checkDueNotifications,20000)}if(window.ClinicData){ClinicData.on('reminders',x=>{if(Array.isArray(x)){reminders=x;dataLoaded=true;renderReminders()}});ClinicData.on('inbox',x=>{if(Array.isArray(x)&&!demoMode){inbox=x;dataLoaded=true;renderInbox()}})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
