(()=>{
const API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-assistant';
const DEMO_ITEMS=[
 {id:'demo-wa-1',channel:'whatsapp',sender_name:'נועה כהן',sender_address:'050-0000000',patient_name:'לולה',received_at:new Date(Date.now()-12*60000).toISOString(),subject:'שאלה אחרי טיפול',body_text:'היי, לולה עברה היום ניקוי שיניים והיא עדיין קצת ישנונית. זה תקין?',preview:'לולה עדיין ישנונית אחרי ניקוי שיניים',category:'אחרי טיפול',priority:'high',status:'needs_attention',metadata:{ai_summary:'לולה עברה היום ניקוי שיניים והבעלים מדווחת על ישנוניות. נדרשת בדיקת איש צוות לפני מתן מענה.',draft_reply:'היי נועה, תודה שעדכנת אותנו. ישנוניות מסוימת יכולה להופיע לאחר טשטוש, אבל כדי לוודא שהכול תקין נבקש לדעת אם לולה ערנית כשקוראים לה, נושמת כרגיל ומצליחה לעמוד. אם יש קושי בנשימה, חוסר תגובה או החמרה — יש ליצור איתנו קשר טלפוני מיד.',assigned_to:'רופא/ה'}},
 {id:'demo-mail-1',channel:'gmail',sender_name:'מעבדת AML',sender_address:'results@example.test',received_at:new Date(Date.now()-48*60000).toISOString(),subject:'תוצאות בדיקה – מיקה',body_text:'מצורפות תוצאות בדיקות המעבדה עבור מיקה, מספר הפניה 4581.',preview:'התקבלו תוצאות מעבדה עבור מיקה',category:'תוצאות מעבדה',priority:'normal',status:'new',metadata:{ai_summary:'התקבל מייל עם תוצאות מעבדה עבור מיקה. יש לשייך לתיק המטופלת ולהעביר לרופא/ה.',draft_reply:'תודה, התוצאות התקבלו והועברו לצוות הרפואי לבדיקה.',assigned_to:'רופא/ה'}},
 {id:'demo-wa-2',channel:'whatsapp',sender_name:'איתי לוי',sender_address:'052-0000000',patient_name:'צ׳ארלי',received_at:new Date(Date.now()-95*60000).toISOString(),subject:'בקשה לקביעת תור',body_text:'אפשר לקבוע לצ׳ארלי חיסון משושה ביום חמישי אחר הצהריים?',preview:'מבקש תור לחיסון משושה ביום חמישי',category:'קביעת תור',priority:'normal',status:'new',metadata:{ai_summary:'בקשה לקביעת תור לחיסון משושה ביום חמישי אחר הצהריים.',draft_reply:'היי איתי, בשמחה. נבדוק את התורים הפנויים ביום חמישי אחר הצהריים ונחזור אליך עם שעה מתאימה.',assigned_to:'קבלה'}}
];
let reminders=[],inbox=[],connections={gmail:false,whatsapp:false},installPrompt=null,dataLoaded=false,dataLoading=null,filter='all',selectedId=null,demoMode=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const meta=x=>x&&typeof x.metadata==='object'&&x.metadata?x.metadata:{};
const channelLabel=x=>x==='gmail'?'מייל':x==='whatsapp'?'ווטסאפ':'ידני';
const priorityLabel=x=>({urgent:'דחוף',high:'חשוב',normal:'רגיל',low:'נמוך'}[x]||'רגיל');
const statusLabel=x=>({new:'חדש',needs_attention:'דורש טיפול',waiting:'ממתין',done:'טופל',archived:'בארכיון'}[x]||'חדש');
async function api(body){if(window.ClinicData)return ClinicData.request('assistant',body);const token=localStorage.getItem('clinic_session_token')||'';if(!token)throw new Error('נדרשת התחברות');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function addCss(){if(document.querySelector('link[data-assistant-center]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='assistant-center.css?v=3';l.dataset.assistantCenter='1';document.head.appendChild(l)}
function addPwa(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.webmanifest?v=1';document.head.appendChild(l)}if('serviceWorker'in navigator)navigator.serviceWorker.register('clinic-sw.js?v=1').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e})}
function inject(){if(document.getElementById('assistant'))return;const app=document.getElementById('app');if(!app)return;const sec=document.createElement('section');sec.id='assistant';sec.className='panel hidden';sec.innerHTML=`
 <div class="assistant-head"><div><h2>מרכז פניות</h2><p>הודעות ווטסאפ ומייל במקום אחד — עם סיכום, עדיפות וטיוטת תשובה.</p></div><div class="assistant-head-actions"><button class="btn" onclick="assistantToggleDemo()" id="assistantDemoBtn">פתיחת הדגמה</button><button class="btn" onclick="assistantEnableNotifications()">🔔 התראות</button></div></div>
 <div id="assistantDemoBanner" class="assistant-demo-banner hidden"><b>מצב הדגמה בלבד</b><span>אלה הודעות לדוגמה. לא נשלח דבר ללקוחות ולא נשמר מידע אמיתי.</span></div>
 <div class="assistant-grid"><article class="assistant-status gmail"><span class="assistant-status-icon">✉️</span><div><small>מייל המרפאה</small><b id="assistantGmailTitle">עדיין לא מחובר</b><em id="assistantGmailState">ממתין לבחירת ספק</em></div></article><article class="assistant-status whatsapp"><span class="assistant-status-icon">💬</span><div><small>ווטסאפ המרפאה</small><b id="assistantWhatsappTitle">עדיין לא מחובר</b><em id="assistantWhatsappState">ממתין למספר ניסיון</em></div></article><article class="assistant-status notify"><span class="assistant-status-icon">🔔</span><div><small>התראות במחשב</small><b id="assistantNotificationTitle">בודק הרשאה...</b><em id="assistantNotificationState">—</em></div></article></div>
 <div class="assistant-kpis"><article><small>דורש טיפול</small><b id="assistantNeedsCount">0</b></article><article><small>דחוף</small><b id="assistantUrgentCount">0</b></article><article><small>טיוטות מוכנות</small><b id="assistantDraftCount">0</b></article></div>
 <div class="assistant-inbox-layout"><section class="assistant-card assistant-list-card"><div class="assistant-card-head"><h3>תיבת פניות</h3><span id="assistantInboxCount" class="assistant-mini-count">0</span></div><div class="assistant-filter-row"><button class="active" onclick="assistantSetFilter('all',this)">הכול</button><button onclick="assistantSetFilter('whatsapp',this)">ווטסאפ</button><button onclick="assistantSetFilter('gmail',this)">מייל</button><button onclick="assistantSetFilter('urgent',this)">דחוף</button></div><div id="assistantInbox" class="assistant-inbox-list"></div></section><section id="assistantConversation" class="assistant-card assistant-conversation"><div class="assistant-empty"><b>בחרי פנייה מהרשימה</b>כאן יופיעו ההודעה המקורית, הסיכום וטיוטת התשובה.</div></section></div>
 <details class="assistant-card assistant-reminders-wrap"><summary>תזכורות פנימיות לצוות <span id="assistantReminderCount" class="assistant-mini-count">0</span></summary><div class="assistant-body"><div class="assistant-reminder-form"><input id="assistantReminderTitle" placeholder="למשל: להתקשר לבעלים של לולה"><input id="assistantReminderAt" type="datetime-local"><textarea id="assistantReminderNotes" placeholder="הערה אופציונלית"></textarea><div class="assistant-reminder-actions"><small>התזכורת משותפת לכל מחשבי המרפאה.</small><button class="btn primary" onclick="assistantSaveReminder()">+ שמירה</button></div></div><div id="assistantReminders" class="assistant-reminders"></div></div></details>`;const anchor=document.getElementById('simulation')||document.getElementById('prices');if(anchor)anchor.insertAdjacentElement('afterend',sec);else app.appendChild(sec);updateNotificationState()}
function fmtDate(v){try{return new Date(v).toLocaleString('he-IL',{dateStyle:'short',timeStyle:'short'})}catch{return v}}
function visibleItems(){return inbox.filter(x=>!['done','archived'].includes(x.status)&&(filter==='all'||x.channel===filter||(filter==='urgent'&&['urgent','high'].includes(x.priority))))}
function renderStats(){const open=inbox.filter(x=>!['done','archived'].includes(x.status));document.getElementById('assistantInboxCount').textContent=String(open.length);document.getElementById('assistantNeedsCount').textContent=String(open.filter(x=>['new','needs_attention'].includes(x.status)).length);document.getElementById('assistantUrgentCount').textContent=String(open.filter(x=>['urgent','high'].includes(x.priority)).length);document.getElementById('assistantDraftCount').textContent=String(open.filter(x=>String(meta(x).draft_reply||'').trim()).length)}
function renderInbox(){const box=document.getElementById('assistantInbox');if(!box)return;renderStats();const rows=visibleItems();if(!rows.length){box.innerHTML='<div class="assistant-empty"><b>אין פניות בתצוגה הזאת</b>אפשר לפתוח את ההדגמה כדי לראות איך המערכת תעבוד.</div>';renderConversation();return}if(!rows.some(x=>String(x.id)===String(selectedId)))selectedId=rows[0].id;box.innerHTML=rows.map(x=>{const m=meta(x),active=String(x.id)===String(selectedId);return `<button class="assistant-inbox-item ${esc(x.priority||'normal')} ${esc(x.channel||'manual')} ${active?'selected':''}" onclick="assistantSelect('${esc(x.id)}')"><div class="assistant-inbox-top"><span class="assistant-channel">${channelLabel(x.channel)}</span><small>${fmtDate(x.received_at)}</small></div><div class="assistant-inbox-title"><h4>${esc(x.sender_name||x.sender_address||'פנייה חדשה')}</h4><span class="priority ${esc(x.priority||'normal')}">${priorityLabel(x.priority)}</span></div><b class="assistant-subject">${esc(x.subject||x.category||'ללא נושא')}</b><p>${esc(m.ai_summary||x.preview||x.body_text||'')}</p><footer><span>${statusLabel(x.status)}</span>${m.draft_reply?'<span>טיוטה מוכנה</span>':''}${x.patient_name?`<span>מטופל/ת: ${esc(x.patient_name)}</span>`:''}</footer></button>`}).join('');renderConversation()}
function renderConversation(){const box=document.getElementById('assistantConversation');if(!box)return;const x=inbox.find(i=>String(i.id)===String(selectedId));if(!x){box.innerHTML='<div class="assistant-empty"><b>בחרי פנייה מהרשימה</b>כאן יופיעו ההודעה המקורית, הסיכום וטיוטת התשובה.</div>';return}const m=meta(x),connected=!!connections[x.channel];box.innerHTML=`<div class="assistant-conversation-head"><div><span class="assistant-channel">${channelLabel(x.channel)}</span><h3>${esc(x.sender_name||x.sender_address||'פנייה חדשה')}</h3><p>${esc(x.sender_address||'')}${x.patient_name?` · ${esc(x.patient_name)}`:''}</p></div><select onchange="assistantChangePriority(this.value)"><option value="normal" ${x.priority==='normal'?'selected':''}>רגיל</option><option value="high" ${x.priority==='high'?'selected':''}>חשוב</option><option value="urgent" ${x.priority==='urgent'?'selected':''}>דחוף</option><option value="low" ${x.priority==='low'?'selected':''}>נמוך</option></select></div><div class="assistant-message-block"><small>ההודעה המקורית</small><b>${esc(x.subject||'')}</b><p>${esc(x.body_text||x.preview||'')}</p></div><div class="assistant-summary-block"><small>סיכום שהבוט הכין</small><p>${esc(m.ai_summary||'עדיין לא נוצר סיכום לפנייה הזאת.')}</p></div><label class="assistant-draft"><span>טיוטת תשובה — אפשר לערוך לפני שליחה</span><textarea id="assistantDraft">${esc(m.draft_reply||'')}</textarea></label><div class="assistant-assignment"><span>אחראי/ת:</span><select id="assistantAssignee"><option ${m.assigned_to==='קבלה'?'selected':''}>קבלה</option><option ${m.assigned_to==='אסיסטנט/ית'?'selected':''}>אסיסטנט/ית</option><option ${m.assigned_to==='רופא/ה'?'selected':''}>רופא/ה</option></select></div><div class="assistant-conversation-actions"><button class="btn" onclick="assistantSaveDraft()">שמירת טיוטה</button><button class="btn" onclick="assistantEscalate()">העברה לרופא/ה</button><button class="btn" onclick="assistantMarkDone()">סימון כטופל</button><button class="btn primary" onclick="assistantSend()" ${connected?'':'disabled'}>${connected?'אישור ושליחה':'שליחה תיפתח לאחר החיבור'}</button></div><div class="assistant-safety-note">הבוט לא שולח אבחנה רפואית או המלצה על תרופה ללא אישור איש צוות.</div>`}
function updateLocal(id,patch){const i=inbox.findIndex(x=>String(x.id)===String(id));if(i<0)return;const current=inbox[i];inbox[i]={...current,...patch,metadata:{...meta(current),...(patch.metadata||{})}}}
async function persist(patch){const id=selectedId;if(!id)return;if(demoMode){updateLocal(id,patch);renderInbox();return}const j=await api({action:'inbox_update',id,...patch});if(j.item){const i=inbox.findIndex(x=>String(x.id)===String(id));if(i>=0)inbox[i]=j.item;ClinicData?.localInbox?.(j.item)}renderInbox()}
window.assistantSetFilter=(next,button)=>{filter=next;document.querySelectorAll('.assistant-filter-row button').forEach(b=>b.classList.toggle('active',b===button));renderInbox()};window.assistantSelect=id=>{selectedId=id;renderInbox()};
window.assistantChangePriority=async value=>{try{await persist({priority:value})}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};
window.assistantSaveDraft=async()=>{const draft=document.getElementById('assistantDraft')?.value.trim()||'',assigned_to=document.getElementById('assistantAssignee')?.value||'קבלה';try{await persist({metadata:{draft_reply:draft,assigned_to}});alert(demoMode?'הטיוטה נשמרה בתוך ההדגמה בלבד':'הטיוטה נשמרה')}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};
window.assistantEscalate=async()=>{const draft=document.getElementById('assistantDraft')?.value.trim()||'';try{await persist({status:'needs_attention',priority:'high',metadata:{draft_reply:draft,assigned_to:'רופא/ה'}})}catch(e){alert('לא הצלחתי להעביר: '+e.message)}};window.assistantMarkDone=async()=>{try{await persist({status:'done'});selectedId=null;renderInbox()}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};
window.assistantSend=()=>{const x=inbox.find(i=>String(i.id)===String(selectedId));if(!x||!connections[x.channel])return alert('החשבון עדיין לא מחובר. בשלב ההדגמה שום דבר לא נשלח ללקוח.');alert('פעולת השליחה תחובר רק לאחר בדיקה עם חשבון הניסיון.')};
window.assistantToggleDemo=()=>{demoMode=!demoMode;document.getElementById('assistantDemoBanner')?.classList.toggle('hidden',!demoMode);const btn=document.getElementById('assistantDemoBtn');if(btn)btn.textContent=demoMode?'סגירת ההדגמה':'פתיחת הדגמה';if(demoMode){inbox=DEMO_ITEMS.map(x=>({...x,metadata:{...x.metadata}}));selectedId=inbox[0].id}else{inbox=[];selectedId=null;dataLoaded=false;load()}renderInbox()};
function renderConnections(){for(const [kind,label] of [['gmail','Gmail'],['whatsapp','Whatsapp']]){const on=!!connections[kind],title=document.getElementById(`assistant${label}Title`),state=document.getElementById(`assistant${label}State`);if(title)title.textContent=on?'מחובר ופועל':'עדיין לא מחובר';if(state){state.textContent=on?'פעיל':'ממתין לחיבור';state.classList.toggle('connected',on)}}}
function renderReminders(){const box=document.getElementById('assistantReminders');if(!box)return;const now=Date.now(),open=reminders.filter(x=>!x.done),done=reminders.filter(x=>x.done).slice(-5);document.getElementById('assistantReminderCount').textContent=String(open.length);const rows=[...open,...done];box.innerHTML=rows.length?rows.map(x=>{const due=!x.done&&new Date(x.remind_at).getTime()<=now;return `<div class="assistant-reminder ${due?'due':''} ${x.done?'done':''}"><div><div class="assistant-reminder-title">${esc(x.title)}</div><div class="assistant-reminder-meta">${fmtDate(x.remind_at)}</div>${x.notes?`<div class="assistant-reminder-note">${esc(x.notes)}</div>`:''}</div><div class="assistant-reminder-buttons">${x.done?`<button onclick="assistantReminderDone(${x.id},false)">החזרה</button>`:`<button class="done" onclick="assistantReminderDone(${x.id},true)">✓ בוצע</button><button class="snooze" onclick="assistantSnooze(${x.id},10)">דחי 10 דק׳</button>`}<button class="delete" onclick="assistantDeleteReminder(${x.id})">מחיקה</button></div></div>`}).join(''):'<div class="assistant-empty"><b>אין תזכורות כרגע</b></div>';checkDueNotifications()}
async function load(){if(dataLoaded||demoMode)return;if(dataLoading)return dataLoading;dataLoading=(async()=>{try{const [j,c]=await Promise.all([window.ClinicData?ClinicData.assistant():api({action:'bootstrap'}),api({action:'connection_status'}).catch(()=>({}))]);reminders=j.reminders||[];inbox=j.inbox||[];connections={gmail:!!c.gmail,whatsapp:!!c.whatsapp};dataLoaded=true;renderReminders();renderConnections();renderInbox()}catch(e){console.warn(e);const box=document.getElementById('assistantInbox');if(box)box.innerHTML='<div class="assistant-empty">לא הצלחתי לטעון כרגע</div>'}finally{dataLoading=null}})();return dataLoading}
function upsertReminder(item){if(!item)return;const i=reminders.findIndex(x=>Number(x.id)===Number(item.id));if(i>=0)reminders[i]=item;else reminders.unshift(item);ClinicData?.localReminder?.(item);dataLoaded=true;renderReminders()}
window.assistantSaveReminder=async()=>{const title=document.getElementById('assistantReminderTitle')?.value.trim(),at=document.getElementById('assistantReminderAt')?.value,notes=document.getElementById('assistantReminderNotes')?.value.trim();if(!title)return alert('צריך לכתוב מה להזכיר');if(!at)return alert('צריך לבחור תאריך ושעה');try{const j=await api({action:'reminder_save',item:{title,remind_at:new Date(at).toISOString(),notes,created_by:'צוות המרפאה'}});document.getElementById('assistantReminderTitle').value='';document.getElementById('assistantReminderAt').value='';document.getElementById('assistantReminderNotes').value='';upsertReminder(j.item)}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};window.assistantReminderDone=async(id,done)=>{try{const j=await api({action:'reminder_done',id,done});upsertReminder(j.item)}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};window.assistantSnooze=async(id,minutes)=>{try{const j=await api({action:'reminder_snooze',id,minutes});clearNotified(id);upsertReminder(j.item)}catch(e){alert('לא הצלחתי לדחות: '+e.message)}};window.assistantDeleteReminder=async id=>{if(!confirm('למחוק את התזכורת?'))return;try{await api({action:'reminder_delete',id});reminders=reminders.filter(x=>Number(x.id)!==Number(id));ClinicData?.removeReminder?.(id);clearNotified(id);renderReminders()}catch(e){alert('לא הצלחתי למחוק: '+e.message)}};
function getNotified(){try{return new Set(JSON.parse(localStorage.getItem('clinic_assistant_notified')||'[]'))}catch{return new Set()}}function saveNotified(s){localStorage.setItem('clinic_assistant_notified',JSON.stringify([...s].slice(-300)))}function clearNotified(id){const s=getNotified();[...s].filter(k=>String(k).startsWith(id+'|')).forEach(k=>s.delete(k));saveNotified(s)}async function notify(title,body){if(!('Notification'in window)||Notification.permission!=='granted')return false;try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'clinic-app-icon.svg',badge:'clinic-app-icon.svg',tag:'clinic-assistant'});return true}new Notification(title,{body});return true}catch{return false}}function checkDueNotifications(){if(!dataLoaded||document.visibilityState==='hidden'||Notification.permission!=='granted')return;const s=getNotified(),now=Date.now();let changed=false;reminders.filter(x=>!x.done&&new Date(x.remind_at).getTime()<=now).forEach(x=>{const k=`${x.id}|${x.remind_at}`;if(s.has(k))return;s.add(k);changed=true;notify('🐾 תזכורת מהמרפאה',x.title+(x.notes?' — '+x.notes:''))});if(changed)saveNotified(s)}
function updateNotificationState(){const title=document.getElementById('assistantNotificationTitle'),state=document.getElementById('assistantNotificationState');if(!title||!state)return;if(!('Notification'in window)){title.textContent='לא נתמך בדפדפן הזה';state.textContent='לא זמין';return}const p=Notification.permission;if(p==='granted'){title.textContent='התראות פעילות';state.textContent='מוכן';state.classList.add('connected')}else if(p==='denied'){title.textContent='ההתראות חסומות';state.textContent='צריך לאשר בהגדרות'}else{title.textContent='אפשר להפעיל';state.textContent='לא אושר עדיין'}}window.assistantEnableNotifications=async()=>{if(!('Notification'in window))return alert('הדפדפן הזה לא תומך בהתראות');const p=await Notification.requestPermission();updateNotificationState();if(p==='granted')notify('עוזר המרפאה פעיל','מכאן נוכל להקפיץ תזכורות במחשב.')};
function maybeLoad(){const sec=document.getElementById('assistant');if(sec&&!sec.classList.contains('hidden'))load()}function boot(){addCss();addPwa();inject();const observer=new MutationObserver(maybeLoad),sec=document.getElementById('assistant');if(sec)observer.observe(sec,{attributes:true,attributeFilter:['class']});maybeLoad();setInterval(checkDueNotifications,20000)}if(window.ClinicData){ClinicData.on('reminders',x=>{if(Array.isArray(x)){reminders=x;dataLoaded=true;renderReminders()}});ClinicData.on('inbox',x=>{if(Array.isArray(x)&&!demoMode){inbox=x;dataLoaded=true;renderInbox()}})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
