(()=>{
const API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-tasks';
const DAYS=['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת'];
const DAY_MAP={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
const AUTHOR='צוות המרפאה';
const $=id=>document.getElementById(id);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jerusalem'});
const currentDay=()=>DAY_MAP[new Date().toLocaleString('en-US',{timeZone:'Asia/Jerusalem',weekday:'short'})];
const heDate=v=>{if(!v)return '';const [y,m,d]=String(v).split('-');return `${d}.${m}.${y}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(body){const token=localStorage.getItem('clinic_session_token')||'';if(!token)throw new Error('נדרשת התחברות');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify(body),cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'שגיאה');return j}
const packWeekly=(day,title,body)=>`[[DAILY]][[DAY]]${day}[[TITLE]]${title}[[BODY]]${body}`;
const packOnce=(date,title,body)=>`[[DAILY]][[ONCE]][[DATE]]${date}[[TITLE]]${title}[[BODY]]${body}`;
function parse(t){const s=String(t.body||'');if(!s.startsWith('[[DAILY]]'))return null;let x=null;const once=s.match(/^\[\[DAILY\]\]\[\[ONCE\]\]\[\[DATE\]\](\d{4}-\d{2}-\d{2})\[\[TITLE\]\]([\s\S]*?)\[\[BODY\]\]([\s\S]*)$/);if(once)x={id:t.id,type:'once',date:once[1],title:once[2],body:once[3],comments:t.comments||[],deleted:false,done:t.status==='closed'};const weekly=s.match(/^\[\[DAILY\]\]\[\[DAY\]\](\d)\[\[TITLE\]\]([\s\S]*?)\[\[BODY\]\]([\s\S]*)$/);if(!x&&weekly)x={id:t.id,type:'weekly',day:+weekly[1],title:weekly[2],body:weekly[3],comments:t.comments||[],deleted:false,done:false};if(!x)return null;for(const c of x.comments){const b=String(c.body||'');if(b==='[[DAILY_DELETE]]')x.deleted=true;if(x.type==='weekly'&&b.startsWith('[[DAILY_EDIT]]')){const q=b.slice(14).match(/^(\d)\|([^|]*)\|([\s\S]*)$/);if(q){x.day=+q[1];x.title=q[2];x.body=q[3]}}if(x.type==='once'&&b.startsWith('[[ONCE_EDIT]]')){const q=b.slice(13).match(/^(\d{4}-\d{2}-\d{2})\|([^|]*)\|([\s\S]*)$/);if(q){x.date=q[1];x.title=q[2];x.body=q[3]}}if(x.type==='weekly'&&b===`[[DAILY_DONE]]${today()}|1`)x.done=true;if(x.type==='weekly'&&b===`[[DAILY_DONE]]${today()}|0`)x.done=false}return x}
let tasks=[],mode='weekly';
function inject(){if($('dailyBoard'))return;const app=$('app');if(!app)return;const overlay=document.createElement('div');overlay.id='dailyBoardOverlay';overlay.className='daily-board-overlay';overlay.onclick=closeDailyBoard;app.appendChild(overlay);const b=document.createElement('section');b.id='dailyBoard';b.className='daily-board';b.innerHTML=`<div class="daily-head"><div class="daily-head-copy"><h3>משימות</h3><div id="dailySub" class="daily-sub"></div></div><button class="daily-close" onclick="closeDailyBoard()" aria-label="סגירה">×</button></div><div class="daily-tabs"><button id="weeklyTab" class="daily-tab active" onclick="setDailyMode('weekly')">משימות קבועות · כל שבוע</button><button id="onceTab" class="daily-tab" onclick="setDailyMode('once')">משימות חד־פעמיות</button></div><div class="daily-workspace"><div class="daily-list-wrap"><div class="daily-panel-title"><h4 id="dailyListTitle"></h4><span id="dailyCount" class="daily-count"></span></div><div id="dailyList"></div></div><aside class="daily-form"><h4 id="dailyFormTitle">הוספת משימה</h4><div id="dailyFormHint" class="form-hint"></div><div id="weeklyDayField"><label for="dailyDay">יום קבוע בשבוע</label><select id="dailyDay">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></div><div id="onceDateField" class="daily-hidden"><label for="dailyDate">תאריך לביצוע</label><input id="dailyDate" type="date"></div><label for="dailyTitle">כותרת</label><input id="dailyTitle" placeholder="למשל: להזמין חיסונים"><label for="dailyBody">פירוט</label><textarea id="dailyBody" placeholder="כל מה שצריך לדעת על המשימה"></textarea><input id="dailyEditId" type="hidden"><div class="daily-form-actions"><button class="btn primary" onclick="saveDailyTask()">שמור</button><button class="btn" onclick="clearDailyForm()">נקה</button></div></aside></div>`;app.appendChild(b)}
window.openDailyBoard=()=>{inject();$('dailyBoard')?.classList.add('open');$('dailyBoardOverlay')?.classList.add('open');render()};
window.closeDailyBoard=()=>{$('dailyBoard')?.classList.remove('open');$('dailyBoardOverlay')?.classList.remove('open')};
window.setDailyMode=m=>{mode=m==='once'?'once':'weekly';$('weeklyTab')?.classList.toggle('active',mode==='weekly');$('onceTab')?.classList.toggle('active',mode==='once');$('weeklyDayField')?.classList.toggle('daily-hidden',mode!=='weekly');$('onceDateField')?.classList.toggle('daily-hidden',mode!=='once');clearDailyForm();render()};
async function load(){try{const j=await api({action:'list'});tasks=(j.items||[]).map(parse).filter(Boolean).filter(x=>!x.deleted);render()}catch(e){const box=$('dailyList');if(box)box.innerHTML=`<div class="daily-empty">לא הצלחתי לטעון משימות: ${esc(e.message)}</div>`}}
function weeklyActions(x){const canDone=x.day===currentDay();return `<div class="daily-actions">${canDone?`<button class="done-action" onclick="toggleDaily(${x.id},${x.done?'false':'true'})">${x.done?'בטלי סימון':'סמני שבוצע'}</button>`:''}<button onclick="editDaily(${x.id})">עריכה</button><button class="delete-action" onclick="deleteDaily(${x.id})">מחיקה</button></div>`}
function weeklyCard(x){return `<div class="daily-item ${x.done?'done':''}"><div class="daily-title">${x.done?'✓ ':''}${esc(x.title)}</div><div class="daily-body">${esc(x.body)}</div>${weeklyActions(x)}</div>`}
function onceCard(x){const overdue=!x.done&&x.date<today();return `<div class="daily-item ${x.done?'done':''} ${overdue?'overdue':''}"><div class="daily-title">${x.done?'✓ ':''}${esc(x.title)}</div><div class="daily-body">${esc(x.body)}</div><div class="daily-meta"><span>${heDate(x.date)}</span>${overdue?'<span class="overdue-tag">עבר התאריך</span>':''}</div><div class="daily-actions">${x.done?`<button onclick="reopenOnce(${x.id})">החזרה לפתוחות</button>`:`<button class="done-action" onclick="completeOnce(${x.id})">סמני שבוצע</button><button onclick="editDaily(${x.id})">עריכה</button>`}<button class="delete-action" onclick="deleteDaily(${x.id})">מחיקה</button></div></div>`}
function render(){if(!$('dailyList'))return;const td=currentDay();const weekly=tasks.filter(x=>x.type==='weekly');const once=tasks.filter(x=>x.type==='once').sort((a,b)=>String(a.date).localeCompare(String(b.date)));const todayWeekly=weekly.filter(x=>x.day===td&&!x.done).length;const dueOnce=once.filter(x=>!x.done&&x.date<=today()).length;$('dailySub').textContent=`היום יום ${DAYS[td]} · ${heDate(today())} · ${todayWeekly+dueOnce} משימות שדורשות תשומת לב`;
if(mode==='weekly'){$('dailyListTitle').textContent='לוח שבועי קבוע';$('dailyCount').textContent=`${weekly.length} משימות`;$('dailyFormTitle').textContent=$('dailyEditId').value?'עריכת משימה קבועה':'משימה קבועה חדשה';$('dailyFormHint').textContent='המשימה תחזור אוטומטית בכל שבוע ביום שתבחרו.';const groups=DAYS.map((d,i)=>{const a=weekly.filter(x=>x.day===i);return `<section class="daily-day-group"><div class="daily-day-label">יום ${d}${i===td?' · היום':''}</div>${a.length?a.map(weeklyCard).join(''):'<div class="daily-empty">אין משימות קבועות ביום הזה</div>'}</section>`});$('dailyList').innerHTML=groups.join('')}else{$('dailyListTitle').textContent='משימות חד־פעמיות';const open=once.filter(x=>!x.done),done=once.filter(x=>x.done);$('dailyCount').textContent=`${open.length} פתוחות`;$('dailyFormTitle').textContent=$('dailyEditId').value?'עריכת משימה חד־פעמית':'משימה חד־פעמית חדשה';$('dailyFormHint').textContent='מתאים לחזרה ללקוח, מעקב בדיקה, הזמנה מסוימת או כל דבר שלא חוזר כל שבוע.';$('dailyList').innerHTML=(open.length?open.map(onceCard).join(''):'<div class="daily-empty">אין משימות חד־פעמיות פתוחות 🎉</div>')+(done.length?`<details class="once-done-section"><summary>הושלמו (${done.length})</summary>${done.map(onceCard).join('')}</details>`:'')}
if(typeof window.dispatchEvent==='function')window.dispatchEvent(new Event('clinicTasksUpdated'))}
window.clinicTodayTaskCount=()=>{const td=currentDay();return tasks.filter(x=>x.type==='weekly'&&x.day===td&&!x.done).length+tasks.filter(x=>x.type==='once'&&!x.done&&x.date<=today()).length};
window.clearDailyForm=()=>{if(!$('dailyEditId'))return;$('dailyEditId').value='';$('dailyTitle').value='';$('dailyBody').value='';$('dailyDay').value=currentDay();$('dailyDate').value=today();if($('dailyFormTitle'))$('dailyFormTitle').textContent=mode==='weekly'?'משימה קבועה חדשה':'משימה חד־פעמית חדשה'};
window.saveDailyTask=async()=>{const id=Number($('dailyEditId').value),title=$('dailyTitle').value.trim(),body=$('dailyBody').value.trim();if(!title)return alert('צריך כותרת');if(!body)return alert('צריך פירוט');try{if(mode==='weekly'){const day=+$('dailyDay').value;if(id)await api({action:'comment',task_id:id,author:AUTHOR,body:`[[DAILY_EDIT]]${day}|${title}|${body}`});else await api({action:'create',item:{audience:'assistants',author:AUTHOR,body:packWeekly(day,title,body)}})}else{const date=$('dailyDate').value||today();if(id)await api({action:'comment',task_id:id,author:AUTHOR,body:`[[ONCE_EDIT]]${date}|${title}|${body}`});else await api({action:'create',item:{audience:'assistants',author:AUTHOR,body:packOnce(date,title,body)}})}clearDailyForm();await load()}catch(e){alert('לא הצלחתי לשמור: '+e.message)}};
window.editDaily=id=>{const x=tasks.find(t=>t.id===id);if(!x)return;mode=x.type;$('weeklyTab')?.classList.toggle('active',mode==='weekly');$('onceTab')?.classList.toggle('active',mode==='once');$('weeklyDayField')?.classList.toggle('daily-hidden',mode!=='weekly');$('onceDateField')?.classList.toggle('daily-hidden',mode!=='once');$('dailyEditId').value=id;$('dailyTitle').value=x.title;$('dailyBody').value=x.body;if(x.type==='weekly')$('dailyDay').value=x.day;else $('dailyDate').value=x.date;render();openDailyBoard()};
window.deleteDaily=async id=>{if(!confirm('למחוק את המשימה?'))return;try{await api({action:'delete',id});clearDailyForm();await load()}catch(e){alert('לא הצלחתי למחוק: '+e.message)}};
window.toggleDaily=async(id,done)=>{try{await api({action:'comment',task_id:id,author:AUTHOR,body:`[[DAILY_DONE]]${today()}|${done?1:0}`});await load()}catch(e){alert('לא הצלחתי לעדכן: '+e.message)}};
window.completeOnce=async id=>{try{await api({action:'close',id,closed_by:AUTHOR});await load()}catch(e){alert('לא הצלחתי לסמן כבוצע: '+e.message)}};
window.reopenOnce=async id=>{try{await api({action:'reopen',id});await load()}catch(e){alert('לא הצלחתי להחזיר את המשימה: '+e.message)}};
function installProductEditClickFix(){if(window.__productEditClickFix)return;window.__productEditClickFix=true;document.addEventListener('click',e=>{const btn=e.target.closest?.('.editbtn');if(!btn)return;const m=String(btn.getAttribute('onclick')||'').match(/openProduct\((\d+)\)/);if(!m)return;e.preventDefault();e.stopImmediatePropagation();const id=Number(m[1]),native=Element.prototype.scrollIntoView;Element.prototype.scrollIntoView=function(){};try{window.openProduct?.(id)}finally{Element.prototype.scrollIntoView=native}},true)}
function loadScript(src,key){if(key&&document.querySelector(`script[data-dynamic="${key}"]`))return;const s=document.createElement('script');s.src=src;s.dataset.dynamic=key||src;document.body.appendChild(s)}
function boot(){if(!localStorage.getItem('clinic_session_token'))return;installProductEditClickFix();inject();clearDailyForm();load();loadScript('clinic-tools.js?v=2','clinic-tools');loadScript('product-pricing.js?v=3','product-pricing');loadScript('subscriptions.js?v=2','subscriptions');loadScript('search-enhancements.js?v=1','search-enhancements');loadScript('simulation.js?v=1','simulation');loadScript('inventory-colors.js?v=2','inventory-colors');loadScript('home-ui.js?v=5','home-ui')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();