(()=>{
function injectPricingFields(){const form=document.getElementById('productForm');if(!form||document.getElementById('prodUnitPrice'))return;const regular=document.getElementById('prodPrice');if(regular)regular.placeholder='מחיר רגיל — להשאיר ריק אם אין מחיר לאריזה';const grid=form.querySelector('.form-grid');if(!grid)return;const unit=document.createElement('input');unit.id='prodUnitPrice';unit.type='number';unit.step='0.01';unit.min='0';unit.placeholder='מחיר ליחידה — למשל 95';const label=document.createElement('input');label.id='prodUnitLabel';label.placeholder='סוג יחידה — למשל: למזרק / לכדור / ליחידה';if(regular){regular.insertAdjacentElement('afterend',unit);unit.insertAdjacentElement('afterend',label)}else{grid.append(unit,label)}
const style=document.createElement('style');style.textContent='.product-prices{margin:5px 0;display:flex;flex-direction:column;gap:2px}.product-prices .price{margin:0}.price-label{font-weight:600;color:#7b8d9e;font-size:.86em}.unit-price{color:#39765d!important}';document.head.appendChild(style)}
const fmt=v=>Number(v).toLocaleString('he-IL',{maximumFractionDigits:2});
window.productCard=function(x,editable){const cur=Number(x.current_qty||0),tar=Number(x.target_qty||0),status=tar>0&&cur<tar?'low':'ok';const hasRegular=x.price_ils!==null&&x.price_ils!==''&&x.price_ils!==undefined;const hasUnit=x.unit_price_ils!==null&&x.unit_price_ils!==''&&x.unit_price_ils!==undefined;let prices='';if(hasRegular||hasUnit){prices='<div class="product-prices">';if(hasRegular)prices+=`<div class="price"><span class="price-label">מחיר רגיל:</span> ${fmt(x.price_ils)} ₪</div>`;if(hasUnit)prices+=`<div class="price unit-price"><span class="price-label">מחיר ליחידה:</span> ${fmt(x.unit_price_ils)} ₪${x.unit_label?' '+esc(x.unit_label):''}</div>`;prices+='</div>'}else prices='<div class="missing-price">⚠️ אין מחיר — צריך לתקן</div>';return `<article class="card product"><div class="pic">${x.image_url?`<img src="${x.image_url}" alt="${esc(x.name)}">`:'📦'}</div><div class="product-info"><h3>${esc(x.name)}</h3><div class="muted cat">${esc(x.category||'')}</div>${prices}<div class="stockbox"><div class="stockline"><span class="target">אמור להיות: ${tar}</span><div class="qtycontrol"><button class="qtybtn" onclick="adjustQty(${x.id},-1)" aria-label="הורד">−</button><span class="qtynum ${status}">${cur}</span><button class="qtybtn" onclick="adjustQty(${x.id},1)" aria-label="הוסף">+</button></div></div></div>${editable?`<button class="btn editbtn" onclick="openProduct(${x.id})">עריכת מוצר</button>`:''}</div></article>`};
window.openProduct=function(id){if(!settingsMode)return;injectPricingFields();const x=products.find(y=>y.id===id);$('prodId').value=x?.id||'';$('prodName').value=x?.name||'';$('prodCat').value=x?.category||'';$('prodPrice').value=x?.price_ils??'';$('prodUnitPrice').value=x?.unit_price_ils??'';$('prodUnitLabel').value=x?.unit_label||'';$('prodTarget').value=x?.target_qty??0;$('prodCurrent').value=x?.current_qty??0;$('prodDetails').value=x?.details||'';productImageData=x?.image_url||'';$('prodDelete').classList.toggle('hidden',!x);$('productForm').classList.remove('hidden');$('productForm').scrollIntoView({behavior:'smooth'})};
window.saveProduct=async function(){injectPricingFields();const id=$('prodId').value,item={name:$('prodName').value.trim(),category:$('prodCat').value.trim()||'אחר',price_ils:$('prodPrice').value,unit_price_ils:$('prodUnitPrice').value,unit_label:$('prodUnitLabel').value.trim(),details:$('prodDetails').value,image_url:productImageData||null,target_qty:$('prodTarget').value,current_qty:$('prodCurrent').value};if(!item.name)return alert('צריך שם מוצר');await api({action:id?'update':'create',id,item});closeProduct();await loadAll()};
function boot(){injectPricingFields();try{renderInventory();if(priceMode==='products')renderProductPrices()}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();