(()=>{
function wrapField(input,labelText){if(!input||input.closest('.product-field'))return input;const w=document.createElement('div');w.className='product-field';const l=document.createElement('label');l.textContent=labelText;input.parentNode.insertBefore(w,input);w.appendChild(l);w.appendChild(input);return input}
function injectPricingFields(){const form=document.getElementById('productForm');if(!form)return;const grid=form.querySelector('.form-grid');if(!grid)return;const regular=document.getElementById('prodPrice');if(regular){regular.type='text';regular.removeAttribute('step');regular.removeAttribute('min');regular.inputMode='text';regular.placeholder='מחיר / טקסט חופשי';wrapField(regular,'מחיר רגיל')}
let unit=document.getElementById('prodUnitPrice');if(!unit){unit=document.createElement('input');unit.id='prodUnitPrice';grid.appendChild(unit)}unit.type='text';unit.removeAttribute('step');unit.removeAttribute('min');unit.inputMode='text';unit.placeholder='מחיר ליחידה / טקסט חופשי';wrapField(unit,'מחיר ליחידה');
let label=document.getElementById('prodUnitLabel');if(!label){label=document.createElement('input');label.id='prodUnitLabel';label.placeholder='למשל: למזרק / לכדור / לאמפולה / מסווג לפי משקל';grid.appendChild(label)}wrapField(label,'סוג היחידה / אופן תמחור');
if(!document.getElementById('productPricingStyles')){const style=document.createElement('style');style.id='productPricingStyles';style.textContent='.product-field{display:flex;flex-direction:column;gap:4px;min-width:0}.product-field label{font-size:12px;font-weight:800;color:#536b80;padding-inline:3px}.product-field input{margin:0!important}.product-prices{margin:6px 0;display:flex;flex-direction:column;gap:3px}.product-prices .price{margin:0}.price-label{font-weight:700;color:#64788a;font-size:.88em}.unit-price{color:#39765d!important}.weight-price{color:#2d658d!important;font-weight:700}.product-desc{font-size:10.5px;line-height:1.35;color:#63798c;margin:6px 0 4px;padding-top:5px;border-top:1px dashed #e2e9ee;overflow-wrap:anywhere}@media(max-width:650px){.product-field label{font-size:11px}.product-desc{font-size:9.5px;display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.product-prices{gap:2px}.product-prices .price{font-size:10px!important}.price-label{font-size:1em}}';document.head.appendChild(style)}}
const priceText=v=>{const s=String(v??'').trim();if(!s)return '—';return /^\d+(?:[.,]\d+)?$/.test(s)?Number(s.replace(',','.')).toLocaleString('he-IL',{maximumFractionDigits:2})+' ₪':esc(s)};
window.productCard=function(x,editable){const cur=Number(x.current_qty||0),tar=Number(x.target_qty||0),status=tar>0&&cur<tar?'low':'ok';const hasRegular=x.price_ils!==null&&x.price_ils!==''&&x.price_ils!==undefined;const hasUnit=x.unit_price_ils!==null&&x.unit_price_ils!==''&&x.unit_price_ils!==undefined;const unitLabel=String(x.unit_label||'').trim();const weightBased=/מסווג לפי משקל|לפי משקל/i.test(unitLabel)||/Bravecto\s*Spot-?On|ברבקטו\s*ספוט/i.test(String(x.name||''));let prices='';if(weightBased){prices='<div class="product-prices">';prices+=`<div class="price weight-price"><span class="price-label">מחיר לפי משקל:</span> ${hasRegular?priceText(x.price_ils):'—'}</div>`;if(hasUnit)prices+=`<div class="price unit-price"><span class="price-label">מחיר ליחידה:</span> ${priceText(x.unit_price_ils)}${unitLabel&&!/מסווג לפי משקל|לפי משקל/i.test(unitLabel)?' '+esc(unitLabel):''}</div>`;prices+='</div>'}else{if(hasRegular)prices+=`<div class="price">${priceText(x.price_ils)}</div>`;else prices+='<div class="missing-price">אין מחיר</div>';if(hasUnit)prices+=`<div class="price unit-price">${priceText(x.unit_price_ils)}${unitLabel?' '+esc(unitLabel):''}</div>`}const desc=x.details?`<div class="product-desc">${esc(x.details)}</div>`:'';return `<article class="card product"><div class="pic">${x.image_url?`<img src="${x.image_url}" alt="${esc(x.name)}">`:'📦'}</div><div class="product-info"><h3>${esc(x.name)}</h3><div class="muted cat">${esc(x.category||'')}</div>${prices}${desc}<div class="stockbox"><div class="stockline"><span class="target">אמור להיות: ${tar}</span><div class="qtycontrol"><button class="qtybtn" onclick="adjustQty(${x.id},-1)" aria-label="הורד">−</button><span class="qtynum ${status}">${cur}</span><button class="qtybtn" onclick="adjustQty(${x.id},1)" aria-label="הוסף">+</button></div></div></div>${editable?`<button class="btn editbtn" onclick="openProduct(${x.id})">עריכת מוצר</button>`:''}</div></article>`};
window.openProduct=function(id){if(!settingsMode)return;injectPricingFields();const x=products.find(y=>y.id===id);$('prodId').value=x?.id||'';$('prodName').value=x?.name||'';$('prodCat').value=x?.category||'';$('prodPrice').value=x?.price_ils??'';$('prodUnitPrice').value=x?.unit_price_ils??'';$('prodUnitLabel').value=x?.unit_label||'';$('prodTarget').value=x?.target_qty??0;$('prodCurrent').value=x?.current_qty??0;$('prodDetails').value=x?.details||'';productImageData=x?.image_url||'';$('prodDelete').classList.toggle('hidden',!x);$('productForm').classList.remove('hidden');$('productForm').scrollIntoView({behavior:'smooth'})};
window.saveProduct=async function(){injectPricingFields();const id=$('prodId').value,item={name:$('prodName').value.trim(),category:$('prodCat').value.trim()||'אחר',price_ils:$('prodPrice').value.trim(),unit_price_ils:$('prodUnitPrice').value.trim(),unit_label:$('prodUnitLabel').value.trim(),details:$('prodDetails').value,image_url:productImageData||null,target_qty:$('prodTarget').value,current_qty:$('prodCurrent').value};if(!item.name)return alert('צריך שם מוצר');await api({action:id?'update':'create',id,item});closeProduct();await loadAll()};
function boot(){injectPricingFields();try{renderInventory();if(priceMode==='products')renderProductPrices()}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();