(()=>{
let inventoryMode='sales',inventoryRefreshTimer=null;
const isMedicine=x=>/^תרופות(?:\s*[—–-]|$)/.test(String(x?.category||''));
const isClinicMed=x=>/שימוש\s*מרפאה/.test(String(x?.category||''));
function wrapField(input,labelText){if(!input||input.closest('.product-field'))return input;const w=document.createElement('div');w.className='product-field';const l=document.createElement('label');l.textContent=labelText;input.parentNode.insertBefore(w,input);w.appendChild(l);w.appendChild(input);return input}
function injectPricingFields(){const form=document.getElementById('productForm');if(!form)return;const grid=form.querySelector('.form-grid');if(!grid)return;const regular=document.getElementById('prodPrice');if(regular){regular.type='text';regular.removeAttribute('step');regular.removeAttribute('min');regular.inputMode='text';regular.placeholder='מחיר / טקסט חופשי';wrapField(regular,'מחיר רגיל')}let unit=document.getElementById('prodUnitPrice');if(!unit){unit=document.createElement('input');unit.id='prodUnitPrice';grid.appendChild(unit)}unit.type='text';unit.placeholder='מחיר ליחידה / טקסט חופשי';wrapField(unit,'מחיר ליחידה');let label=document.getElementById('prodUnitLabel');if(!label){label=document.createElement('input');label.id='prodUnitLabel';label.placeholder='למשל: למזרק / לכדור / לאמפולה / מסווג לפי משקל';grid.appendChild(label)}wrapField(label,'סוג היחידה / אופן תמחור')}
function injectInventoryModes(){const section=document.getElementById('inventory');if(!section||document.getElementById('inventoryModes'))return;const bar=section.querySelector('.sectionbar');const modes=document.createElement('div');modes.id='inventoryModes';modes.className='row inventory-modes';modes.innerHTML='<button id="saleInventoryBtn" class="inventory-mode active" onclick="showInventoryMode(\'sales\')">מוצרים למכירה</button><button id="medInventoryBtn" class="inventory-mode" onclick="showInventoryMode(\'meds\')">תרופות</button>';bar?.insertAdjacentElement('afterend',modes)}
const cleanDetails=v=>String(v??'').split(/(?<=[.!?])\s+|\n+/).filter(s=>s.trim()&&!/(?:מחיר\s*מסומן|מחיר\s*:|₪)/i.test(s)).join(' ').replace(/\s{2,}/g,' ').trim();
const priceText=v=>{const s=String(v??'').trim();if(!s)return '—';return /^\d+(?:[.,]\d+)?$/.test(s)?Number(s.replace(',','.')).toLocaleString('he-IL',{maximumFractionDigits:2})+' ₪':esc(s)};
window.productCard=function(x,editable){const cur=Number(x.current_qty||0),tar=Number(x.target_qty||0),status=tar>0&&cur<tar?'low':'ok';const hasRegular=x.price_ils!==null&&x.price_ils!==''&&x.price_ils!==undefined;const hasUnit=x.unit_price_ils!==null&&x.unit_price_ils!==''&&x.unit_price_ils!==undefined;const unitLabel=String(x.unit_label||'').trim();let prices='';if(!isClinicMed(x)){if(hasRegular)prices+=`<div class="price">${priceText(x.price_ils)}</div>`;else if(!hasUnit)prices+='<div class="missing-price">אין מחיר</div>';if(hasUnit)prices+=`<div class="price unit-price">${priceText(x.unit_price_ils)}${unitLabel?' '+esc(unitLabel):''}</div>`}const badge=isMedicine(x)?`<div class="med-badge ${isClinicMed(x)?'med-clinic':'med-sale'}">${isClinicMed(x)?'לשימוש המרפאה':'למכירה'}</div>`:'';const clean=cleanDetails(x.details);const desc=clean?`<div class="product-desc">${esc(clean)}</div>`:'';return `<article class="card product"><div class="pic">${x.image_url?`<img src="${x.image_url}" alt="${esc(x.name)}">`:(isMedicine(x)?'💊':'📦')}</div><div class="product-info"><h3>${esc(x.name)}</h3><div class="muted cat">${esc(x.category||'')}</div>${badge}${prices}${desc}<div class="stockbox"><div class="stockline"><span class="target">אמור להיות: ${tar}</span><div class="qtycontrol"><button class="qtybtn" onclick="adjustQty(${x.id},-1)">−</button><span class="qtynum ${status}">${cur}</span><button class="qtybtn" onclick="adjustQty(${x.id},1)">+</button></div></div></div>${editable?`<button class="btn editbtn" onclick="openProduct(${x.id})">עריכת מוצר</button>`:''}</div></article>`};
window.fillFilters=function(){const inv=products.filter(x=>inventoryMode==='meds'?isMedicine(x):!isMedicine(x));const a=[...new Set(inv.map(x=>x.category).filter(Boolean))].sort(),b=[...new Set(prices.map(x=>x.category).filter(Boolean))].sort();const invSelect=$('inventoryCategory');const prev=invSelect?.value||'';if(invSelect){invSelect.innerHTML='<option value="">כל הקטגוריות</option>'+a.map(c=>`<option>${esc(c)}</option>`).join('');if(a.includes(prev))invSelect.value=prev}if($('priceCategory'))$('priceCategory').innerHTML='<option value="">כל הקטגוריות</option>'+b.map(c=>`<option>${esc(c)}</option>`).join('')};
window.showInventoryMode=function(mode){inventoryMode=mode==='meds'?'meds':'sales';document.getElementById('saleInventoryBtn')?.classList.toggle('active',inventoryMode==='sales');document.getElementById('medInventoryBtn')?.classList.toggle('active',inventoryMode==='meds');const h=document.querySelector('#inventory .sectionbar h2');if(h)h.textContent=inventoryMode==='meds'?'מלאי תרופות':'מוצרים למכירה';fillFilters();renderInventory()};
window.renderInventory=function(){const q=($('inventorySearch')?.value||'').trim().toLowerCase(),cat=$('inventoryCategory')?.value||'',grid=$('inventoryGrid');if(!grid)return;const arr=products.filter(x=>(inventoryMode==='meds'?isMedicine(x):!isMedicine(x))&&(!cat||x.category===cat)&&(!q||(x.name+' '+(x.category||'')+' '+(x.details||'')).toLowerCase().includes(q)));grid.innerHTML=arr.map(x=>productCard(x,settingsMode)).join('')||'<p class="muted">אין תוצאות</p>'};
window.openProduct=function(id){if(!settingsMode)return;injectPricingFields();const x=products.find(y=>y.id===id);$('prodId').value=x?.id||'';$('prodName').value=x?.name||'';$('prodCat').value=x?.category||(inventoryMode==='meds'?'תרופות — שימוש מרפאה':'');$('prodPrice').value=x?.price_ils??'';$('prodUnitPrice').value=x?.unit_price_ils??'';$('prodUnitLabel').value=x?.unit_label||'';$('prodTarget').value=x?.target_qty??0;$('prodCurrent').value=x?.current_qty??0;$('prodDetails').value=cleanDetails(x?.details);productImageData=x?.image_url||'';$('prodDelete').classList.toggle('hidden',!x);$('productForm').classList.remove('hidden')};
window.saveProduct=async function(){const id=$('prodId').value,item={name:$('prodName').value.trim(),category:$('prodCat').value.trim()||(inventoryMode==='meds'?'תרופות — שימוש מרפאה':'אחר'),price_ils:$('prodPrice').value.trim(),unit_price_ils:$('prodUnitPrice').value.trim(),unit_label:$('prodUnitLabel').value.trim(),details:cleanDetails($('prodDetails').value),image_url:productImageData||null,target_qty:$('prodTarget').value,current_qty:$('prodCurrent').value};if(!item.name)return alert('צריך שם מוצר');await api({action:id?'update':'create',id,item});closeProduct();await loadAll()};

/* Protocol builder */
let protocols=JSON.parse(localStorage.getItem('clinicProtocols')||'[]'),editingProtocol=null;
const saveProtocols=()=>localStorage.setItem('clinicProtocols',JSON.stringify(protocols));
function protocolStyles(){if(document.getElementById('protocolStyles'))return;const s=document.createElement('style');s.id='protocolStyles';s.textContent='.protocol-head{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:14px}.protocol-list{display:grid;gap:12px}.protocol-card{padding:16px}.protocol-card h3{margin:0 0 5px;color:#173a5f}.protocol-fields{display:grid;gap:7px;margin-top:12px}.protocol-line{padding:9px 11px;background:#f7fafc;border:1px solid #e3ebf1;border-radius:9px}.protocol-line b{display:block;color:#355873;font-size:12px;margin-bottom:3px}.protocol-editor{padding:16px;margin-bottom:14px}.protocol-field-edit{display:grid;grid-template-columns:1fr 2fr auto;gap:7px;margin:7px 0}.protocol-editor input,.protocol-editor textarea{width:100%;padding:10px;border:1px solid #d7e1e9;border-radius:9px}.protocol-editor textarea{min-height:70px;resize:vertical}@media(max-width:650px){.protocol-field-edit{grid-template-columns:1fr}.protocol-field-edit .danger{width:max-content}}';document.head.appendChild(s)}
function injectProtocols(){const sec=document.getElementById('protocols');if(!sec)return;protocolStyles();sec.innerHTML='<div class="protocol-head"><h2>פרוטוקולים</h2><button id="addProtocolBtn" class="btn primary" onclick="openProtocolEditor()">+ פרוטוקול חדש</button></div><div id="protocolEditor"></div><div id="protocolList" class="protocol-list"></div>';renderProtocols()}
window.openProtocolEditor=function(i=null){editingProtocol=i;const p=i===null?{title:'',category:'',fields:[{label:'',value:''}]}:JSON.parse(JSON.stringify(protocols[i]));$('protocolEditor').innerHTML=`<div class="card protocol-editor"><h3>${i===null?'פרוטוקול חדש':'עריכת פרוטוקול'}</h3><input id="protocolTitle" placeholder="שם הפרוטוקול" value="${esc(p.title||'')}"><input id="protocolCategory" placeholder="קטגוריה (למשל: הרדמה, אשפוז, חירום)" value="${esc(p.category||'')}"><div id="protocolFieldEditor"></div><div class="row"><button class="btn" onclick="addProtocolField()">+ הוספת שדה</button><button class="btn primary" onclick="saveProtocol()">שמור פרוטוקול</button><button class="btn" onclick="closeProtocolEditor()">ביטול</button>${i!==null?'<button class="btn danger" onclick="deleteProtocol()">מחיקת פרוטוקול</button>':''}</div></div>`;window._protocolDraft=p;renderProtocolFieldEditor()};
function renderProtocolFieldEditor(){const d=$('protocolFieldEditor');if(!d)return;d.innerHTML=window._protocolDraft.fields.map((f,i)=>`<div class="protocol-field-edit"><input placeholder="כותרת השדה" value="${esc(f.label||'')}" oninput="_protocolDraft.fields[${i}].label=this.value"><textarea placeholder="תוכן / הוראות" oninput="_protocolDraft.fields[${i}].value=this.value">${esc(f.value||'')}</textarea><button class="btn danger" onclick="removeProtocolField(${i})">הסר שדה</button></div>`).join('')}
window.addProtocolField=()=>{window._protocolDraft.fields.push({label:'',value:''});renderProtocolFieldEditor()};
window.removeProtocolField=i=>{window._protocolDraft.fields.splice(i,1);renderProtocolFieldEditor()};
window.closeProtocolEditor=()=>{$('protocolEditor').innerHTML='';editingProtocol=null};
window.saveProtocol=function(){const title=$('protocolTitle').value.trim();if(!title)return alert('צריך שם לפרוטוקול');window._protocolDraft.title=title;window._protocolDraft.category=$('protocolCategory').value.trim();if(editingProtocol===null)protocols.push(window._protocolDraft);else protocols[editingProtocol]=window._protocolDraft;saveProtocols();closeProtocolEditor();renderProtocols()};
window.deleteProtocol=function(){if(editingProtocol===null)return;if(!confirm('למחוק את הפרוטוקול?'))return;protocols.splice(editingProtocol,1);saveProtocols();closeProtocolEditor();renderProtocols()};
window.editProtocol=i=>openProtocolEditor(i);
function renderProtocols(){const list=$('protocolList');if(!list)return;list.innerHTML=protocols.length?protocols.map((p,i)=>`<div class="card protocol-card"><h3>${esc(p.title)}</h3>${p.category?`<div class="muted">${esc(p.category)}</div>`:''}<div class="protocol-fields">${(p.fields||[]).map(f=>`<div class="protocol-line"><b>${esc(f.label||'שדה')}</b><div>${esc(f.value||'').replace(/\n/g,'<br>')}</div></div>`).join('')}</div><button class="btn editbtn" onclick="editProtocol(${i})">עריכה</button></div>`).join(''):'<div class="card protocol-card muted">עדיין לא הוספתם פרוטוקולים. לחצי על “+ פרוטוקול חדש”.</div>'}
function boot(){injectPricingFields();injectInventoryModes();injectProtocols();try{showInventoryMode('sales')}catch{}inventoryRefreshTimer=setInterval(()=>{try{if(products?.length){fillFilters();renderInventory();clearInterval(inventoryRefreshTimer)}}catch{}},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();