(()=>{
const API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-api';
const escQ=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nQ=v=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
const moneyQ=v=>Math.round(nQ(v)).toLocaleString('he-IL')+' ₪';
const goldQ=(v,d)=>Math.ceil(nQ(v)*(1-(nQ(d)||0)/100));
const uidQ=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const TOPICS=['סירוס','עיקור','אשך טמיר','קיסרי','פיומטרה','ניקוי שיניים','עקירות שיניים','מסה / הסרת גידול','הרניה','מערכת עיכול','מערכת שתן','עיניים','אוזניים','חבישה ופצעים','אשפוז','בדיקות דם','חיסונים וטיפולים מונעים','אחר'];
let state={items:[],saved:[],savedId:null};
async function apiQ(body){const token=localStorage.getItem('clinic_session_token')||'';if(!token)throw new Error('נדרשת התחברות');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function cssQ(){if(document.querySelector('link[data-simulation-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='simulation.css?v=1';l.dataset.simulationCss='1';document.head.appendChild(l)}
function productAllowed(x){try{if(typeof isClinicMed==='function'&&isClinicMed(x))return false}catch{}const raw=String(x?.unit_price_ils??'').trim()||String(x?.price_ils??'').trim();return raw!==''&&Number.isFinite(Number(raw))}
function catalogQ(){const out=[];try{if(typeof prices!=='undefined'&&Array.isArray(prices)){for(const x of prices){const min=nQ(x.regular_price_min),max=nQ(x.regular_price_max||x.regular_price_min);if(!min)continue;out.push({key:'price:'+x.id,source:'מחירון',sourceId:x.id,name:String(x.name||''),category:String(x.category||''),min,max:max||min,discount:nQ(x.discount_percent??20),note:String(x.note||''),aliases:''})}}}catch{}
try{if(typeof products!=='undefined'&&Array.isArray(products)){for(const x of products){if(!productAllowed(x))continue;const raw=String(x.unit_price_ils??'').trim()||String(x.price_ils??'').trim(),v=nQ(raw);if(!v)continue;out.push({key:'product:'+x.id,source:'מוצר',sourceId:x.id,name:String(x.name||''),category:String(x.category||''),min:v,max:v,discount:20,note:String(x.unit_label||x.details||''),aliases:''})}}}catch{}
return out}
function cryptorchidGroupQ(){const all=catalogQ(),low=all.find(x=>x.source==='מחירון'&&x.name.includes('סירוס אשך טמיר בתעלה')),high=all.find(x=>x.source==='מחירון'&&x.name.includes('סירוס אשך טמיר בחלל הבטן'));if(!low||!high)return null;return {key:'smart:cryptorchid',source:'טווח מותנה',sourceId:null,name:'סירוס אשך טמיר — לפי מיקום האשך',category:'כירורגיה / מערכת מין',min:low.min,max:high.min,discount:Math.min(low.discount,high.discount),note:`בתעלה: ${moneyQ(low.min)} · בחלל הבטן: ${moneyQ(high.min)}. אם המיקום אינו ידוע מראש, המחיר הסופי נקבע לפי המיקום שנמצא בפועל.`,aliases:'אשך טמיר אשך תמיר סירוס אשך',smart:true,choices:[{value:'range',label:'עדיין לא ידוע — הצג טווח'},{value:'low',label:'האשך בתעלה'},{value:'high',label:'האשך בחלל הבטן'}]}}
function searchQ(q){const s=String(q||'').trim().toLowerCase();if(!s)return [];const all=catalogQ(),arr=all.filter(x=>`${x.name} ${x.category} ${x.note} ${x.aliases||''}`.toLowerCase().includes(s));const smart=cryptorchidGroupQ();if(smart&&`${smart.name} ${smart.aliases}`.toLowerCase().includes(s))arr.unshift(smart);return arr.slice(0,30)}
function isRangeQ(x){return nQ(x.max)>nQ(x.min)}
function priceTextQ(min,max){return nQ(max)>nQ(min)?`${moneyQ(min)}–${moneyQ(max)}`:moneyQ(min)}
function uncertaintyLabelQ(x){if(x.smart)return 'מחיר לפי מיקום / מצב';if(isRangeQ(x))return 'טווח מחיר';return ''}
function resultHtmlQ(x){const gmin=goldQ(x.min,x.discount),gmax=goldQ(x.max,x.discount),warn=isRangeQ(x)||x.note?`<div class="sim-result-note">${escQ(x.note||'המחיר מוצג כטווח לפי חומרת המצב.')}</div>`:'';return `<div class="sim-result ${x.smart?'smart':''}"><div class="sim-result-main"><div class="sim-result-name">${escQ(x.name)}</div><div class="sim-result-meta">${escQ(x.category)}${uncertaintyLabelQ(x)?' · '+escQ(uncertaintyLabelQ(x)):''}</div><div class="sim-result-prices"><span class="sim-chip">רגיל <b>${priceTextQ(x.min,x.max)}</b></span><span class="sim-chip gold">מנוי זהב <b>${priceTextQ(gmin,gmax)}</b></span>${isRangeQ(x)?'<span class="sim-chip range">טווח לפי מצב</span>':''}</div>${warn}</div><button class="btn primary sim-add" onclick="simulationAdd('${escQ(x.key)}')">+ הוספה</button></div>`}
window.simulationSearch=function(){const box=document.getElementById('simulationResults'),q=document.getElementById('simulationSearch')?.value||'';if(!box)return;const arr=searchQ(q);box.innerHTML=q.trim()?(arr.length?arr.map(resultHtmlQ).join(''):'<div class="sim-empty">לא נמצאו תוצאות</div>'):''}
window.simulationAdd=function(key){let x;if(key==='smart:cryptorchid')x=cryptorchidGroupQ();else x=catalogQ().find(y=>y.key===key);if(!x)return;state.items.push({uid:uidQ(),key:x.key,source:x.source,sourceId:x.sourceId,name:x.name,category:x.category,min:x.min,max:x.max,discount:x.discount,note:x.note,smart:!!x.smart,choices:x.choices||null,mode:'range',qty:1});const s=document.getElementById('simulationSearch');if(s)s.value='';const r=document.getElementById('simulationResults');if(r)r.innerHTML='';renderCartQ()}
function effectiveQ(x){if(x.mode==='low')return [nQ(x.min),nQ(x.min)];if(x.mode==='high')return [nQ(x.max),nQ(x.max)];return [nQ(x.min),nQ(x.max)]}
function lineTotalsQ(x){const [a,b]=effectiveQ(x),qty=Math.max(1,Math.floor(nQ(x.qty)||1));return {rmin:a*qty,rmax:b*qty,gmin:goldQ(a,x.discount)*qty,gmax:goldQ(b,x.discount)*qty}}
function totalsQ(){return state.items.reduce((t,x)=>{const q=lineTotalsQ(x);t.rmin+=q.rmin;t.rmax+=q.rmax;t.gmin+=q.gmin;t.gmax+=q.gmax;return t},{rmin:0,rmax:0,gmin:0,gmax:0})}
function modeOptionsQ(x){if(!isRangeQ(x))return '';const choices=x.choices||[{value:'range',label:'הצג טווח'},{value:'low',label:'לפי המחיר הנמוך'},{value:'high',label:'לפי המחיר הגבוה'}];return `<div class="sim-line-range"><span class="sim-chip range">${x.smart?'משתנה לפי מיקום':'משתנה לפי מצב'}</span><select onchange="simulationMode('${x.uid}',this.value)">${choices.map(c=>`<option value="${c.value}" ${x.mode===c.value?'selected':''}>${escQ(c.label)}</option>`).join('')}</select></div>`}
function lineHtmlQ(x){const q=lineTotalsQ(x),warning=(x.note||isRangeQ(x))?`<div class="sim-line-warning">${escQ(x.note||'המחיר עשוי להשתנות לפי חומרת המצב.')}</div>`:'';return `<div class="sim-line"><div class="sim-line-info"><div class="sim-line-name">${escQ(x.name)}</div><div class="sim-line-category">${escQ(x.category)}</div>${modeOptionsQ(x)}${warning}</div><div class="sim-qty"><button onclick="simulationQty('${x.uid}',-1)">−</button><input type="number" min="1" value="${Math.max(1,Math.floor(nQ(x.qty)||1))}" onchange="simulationQtySet('${x.uid}',this.value)"><button onclick="simulationQty('${x.uid}',1)">+</button></div><div><div class="sim-line-price"><span>רגיל</span><b>${priceTextQ(q.rmin,q.rmax)}</b></div><div class="sim-line-price"><span>מנוי זהב</span><b class="gold-price">${priceTextQ(q.gmin,q.gmax)}</b></div></div><button class="sim-remove" onclick="simulationRemove('${x.uid}')">הסרה</button></div>`}
function renderCartQ(){const list=document.getElementById('simulationCartList'),count=document.getElementById('simulationItemCount'),tot=document.getElementById('simulationTotals');if(count)count.textContent=state.items.length?`${state.items.length} פריטים`:'ריקה';if(list)list.innerHTML=state.items.length?state.items.map(lineHtmlQ).join(''):'<div class="sim-empty">חפשי פרוצדורה או מוצר והוסיפי אותם לסימולציה.</div>';if(tot){const t=totalsQ(),range=t.rmax>t.rmin||t.gmax>t.gmin;tot.innerHTML=`<div class="sim-total-box"><span>סה״כ מחיר רגיל</span><b>${priceTextQ(t.rmin,t.rmax)}</b></div><div class="sim-total-box gold"><span>סה״כ מנוי זהב</span><b>${priceTextQ(t.gmin,t.gmax)}</b></div><div class="sim-total-hint">${range?'הסכום מוצג כטווח כי לפחות אחד מהפריטים תלוי במצב, חומרה או מיקום. אפשר לבחור בכל שורה מחיר נמוך/גבוה כשכבר יודעים את המצב.':'הסכום מחושב אוטומטית לפי הפריטים והכמויות שנבחרו.'}</div>`}updateSaveFieldsQ()}
window.simulationQty=function(uid,d){const x=state.items.find(i=>i.uid===uid);if(!x)return;x.qty=Math.max(1,Math.floor(nQ(x.qty)||1)+Number(d||0));renderCartQ()}
window.simulationQtySet=function(uid,v){const x=state.items.find(i=>i.uid===uid);if(!x)return;x.qty=Math.max(1,Math.floor(nQ(v)||1));renderCartQ()}
window.simulationMode=function(uid,mode){const x=state.items.find(i=>i.uid===uid);if(!x)return;x.mode=['range','low','high'].includes(mode)?mode:'range';renderCartQ()}
window.simulationRemove=function(uid){state.items=state.items.filter(i=>i.uid!==uid);renderCartQ()}
window.simulationClear=function(){if(state.items.length&&!confirm('לנקות את הסימולציה הנוכחית?'))return;state.items=[];state.savedId=null;const a=document.getElementById('simSaveName'),b=document.getElementById('simSaveNotes');if(a)a.value='';if(b)b.value='';renderCartQ()}
function topicOptionsQ(){const existing=state.saved.map(x=>String(x.topic||'')).filter(Boolean),all=[...new Set([...TOPICS,...existing])];return all}
function renderTopicQ(selected=''){const sel=document.getElementById('simSaveTopic');if(!sel)return;const cur=selected||sel.value||TOPICS[0];sel.innerHTML=topicOptionsQ().map(x=>`<option value="${escQ(x)}" ${x===cur?'selected':''}>${escQ(x)}</option>`).join('')+'<option value="__new__">+ נושא חדש</option>';if(!sel.value)sel.value=cur}
window.simulationTopicChanged=function(){const s=document.getElementById('simSaveTopic'),n=document.getElementById('simNewTopic');if(n)n.classList.toggle('hidden',s?.value!=='__new__')}
function updateSaveFieldsQ(){const btn=document.getElementById('simSaveBtn');if(btn)btn.textContent=state.savedId?'עדכון סימולציה שמורה':'שמירת הסימולציה'}
function dateQ(v){try{return new Date(v).toLocaleString('he-IL',{dateStyle:'short',timeStyle:'short'})}catch{return ''}}
function savedHtmlQ(x){const total=priceTextQ(x.regular_min,x.regular_max);return `<div class="sim-saved"><b>${escQ(x.name)}</b><small>${escQ(x.topic||'אחר')} · ${escQ(dateQ(x.updated_at))}</small><div class="sim-saved-total">סה״כ רגיל: ${escQ(total)}</div><div class="sim-saved-actions"><button class="sim-load" onclick="simulationLoadSaved(${Number(x.id)})">פתיחה</button><button class="sim-delete" onclick="simulationDeleteSaved(${Number(x.id)})">מחיקה</button></div></div>`}
function renderSavedQ(){const box=document.getElementById('simSavedList');if(box)box.innerHTML=state.saved.length?state.saved.map(savedHtmlQ).join(''):'<div class="muted" style="font-size:11px">עדיין אין סימולציות שמורות.</div>';renderTopicQ()}
async function loadSavedQ(){try{const j=await apiQ({action:'quote_list'});state.saved=j.items||[];renderSavedQ()}catch(e){console.error(e)}}
window.openSimulationDrawer=function(){document.getElementById('simulationDrawer')?.classList.add('open');document.getElementById('simulationDrawerOverlay')?.classList.add('open');loadSavedQ()}
window.closeSimulationDrawer=function(){document.getElementById('simulationDrawer')?.classList.remove('open');document.getElementById('simulationDrawerOverlay')?.classList.remove('open')}
window.simulationSave=async function(){if(!state.items.length)return alert('הסימולציה ריקה');const name=document.getElementById('simSaveName')?.value.trim()||'';if(!name)return alert('צריך לתת שם לסימולציה');const sel=document.getElementById('simSaveTopic'),custom=document.getElementById('simNewTopic')?.value.trim()||'',topic=sel?.value==='__new__'?custom:(sel?.value||'אחר');if(!topic)return alert('צריך לבחור או ליצור נושא');const t=totalsQ(),payload={name,topic,notes:document.getElementById('simSaveNotes')?.value.trim()||'',items:state.items,regular_min:t.rmin,regular_max:t.rmax,gold_min:t.gmin,gold_max:t.gmax};try{const j=await apiQ({action:'quote_save',id:state.savedId||undefined,item:payload});state.savedId=j.item?.id||state.savedId;await loadSavedQ();updateSaveFieldsQ();alert('הסימולציה נשמרה')}catch(e){alert('לא הצלחתי לשמור את הסימולציה') }}
window.simulationLoadSaved=function(id){const x=state.saved.find(y=>Number(y.id)===Number(id));if(!x)return;if(state.items.length&&!confirm('לפתוח את הסימולציה השמורה במקום הנוכחית?'))return;state.savedId=Number(x.id);state.items=(Array.isArray(x.items)?x.items:[]).map(i=>({...i,uid:i.uid||uidQ(),qty:Math.max(1,Math.floor(nQ(i.qty)||1)),mode:['range','low','high'].includes(i.mode)?i.mode:'range'}));const name=document.getElementById('simSaveName'),notes=document.getElementById('simSaveNotes');if(name)name.value=x.name||'';if(notes)notes.value=x.notes||'';renderTopicQ(x.topic||'אחר');simulationTopicChanged();renderCartQ();closeSimulationDrawer();window.scrollTo({top:0,behavior:'smooth'})}
window.simulationDeleteSaved=async function(id){const x=state.saved.find(y=>Number(y.id)===Number(id));if(!confirm(`למחוק את "${x?.name||'הסימולציה'}"?`))return;try{await apiQ({action:'quote_delete',id});if(Number(state.savedId)===Number(id))state.savedId=null;await loadSavedQ();updateSaveFieldsQ()}catch{alert('לא הצלחתי למחוק') }}
function injectQ(){if(document.getElementById('simulation'))return true;const anchor=document.getElementById('prices')||document.querySelector('#app .panel');if(!anchor)return false;cssQ();const sec=document.createElement('section');sec.id='simulation';sec.className='panel hidden';sec.innerHTML=`<div class="sim-head"><div><h2>סימולציית הצעת מחיר</h2><p>מוסיפים פרוצדורות ומוצרים, והמערכת מחשבת לבד מחיר רגיל, מנוי זהב וטווחים לפי מצב.</p></div><div class="sim-head-actions"><button class="btn" onclick="simulationClear()">סימולציה חדשה</button><button class="btn sim-save-toggle" onclick="openSimulationDrawer()">שמירה / סימולציות שמורות</button></div></div><div class="sim-workspace"><div class="card sim-search-card"><label>מה להוסיף להצעת המחיר?</label><div class="sim-search-wrap"><input id="simulationSearch" placeholder="לדוגמה: אשך טמיר, ניקוי שיניים, בדיקות דם..." oninput="simulationSearch()"></div><div id="simulationResults" class="sim-search-results"></div></div><div class="card sim-cart"><div class="sim-cart-title"><h3>הסימולציה הנוכחית</h3><small id="simulationItemCount">ריקה</small></div><div id="simulationCartList"></div><div id="simulationTotals" class="sim-total"></div></div></div><div id="simulationDrawerOverlay" class="sim-drawer-overlay" onclick="closeSimulationDrawer()"></div><aside id="simulationDrawer" class="sim-drawer"><div class="sim-drawer-head"><h3>שמירה וסימולציות שמורות</h3><button class="sim-drawer-close" onclick="closeSimulationDrawer()">×</button></div><div class="card sim-save-form"><label>שם הסימולציה</label><input id="simSaveName" placeholder="למשל: אשך טמיר - בובי"><label>נושא</label><select id="simSaveTopic" onchange="simulationTopicChanged()"></select><input id="simNewTopic" class="sim-topic-new hidden" placeholder="שם נושא חדש"><div class="sim-topics-hint">הנושאים עוזרים למצוא מהר הצעות דומות בעתיד.</div><label>הערה אופציונלית</label><textarea id="simSaveNotes" placeholder="למשל: הצעת מחיר ללקוח שמגיע מחר"></textarea><div class="row"><button id="simSaveBtn" class="btn primary" onclick="simulationSave()">שמירת הסימולציה</button></div></div><div class="sim-saved-title">סימולציות שמורות</div><div id="simSavedList" class="sim-saved-list"></div></aside>`;anchor.insertAdjacentElement('afterend',sec);renderTopicQ();renderCartQ();loadSavedQ();return true}
let tries=0;const timer=setInterval(()=>{tries++;if(injectQ()||tries>50)clearInterval(timer)},200);if(document.readyState!=='loading')injectQ();
})();