(()=>{
const TASK_API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-tasks';
const STAFF=['ד״ר לזר ג׳רסי','ד״ר ג׳מיל טנוס','ד״ר הדס לוי','קים','רננה','אמילי','זהר','רוני','אביטל','דורין'];
let currentAudience='doctors',taskView='open',extrasStarted=false;
const taskLists={open:[],closed:[]},loaded={open:false,closed:false},details=new Map();
const token=()=>localStorage.getItem('clinic_session_token')||'';
const escT=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const fmt=d=>new Date(d).toLocaleString('he-IL',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
const options=()=>`<option value="" selected disabled>בחרו מי רשם/ה</option>`+STAFF.map(n=>`<option value="${escT(n)}">${escT(n)}</option>`).join('');
const packTask=(title,body)=>`[[TITLE]]${title}\n[[BODY]]${body}`;
function unpackTask(raw){const s=String(raw||'');const m=s.match(/^\[\[TITLE\]\]([\s\S]*?)\n\[\[BODY\]\]([\s\S]*)$/);return m?{title:m[1].trim(),body:m[2].trim()}:{title:'ללא כותרת',body:s}}
async function taskApi(body){if(window.ClinicData)return ClinicData.request('tasks',body);const r=await fetch(TASK_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token()},body:JSON.stringify(body),cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function showLogin(msg=''){document.getElementById('app')?.classList.add('hidden');document.getElementById('login')?.classList.remove('hidden');const e=document.getElementById('loginErr');if(e)e.textContent=msg}
function applyUiTweaks(){if(document.getElementById('clinicUiTweaks'))return;const s=document.createElement('style');s.id='clinicUiTweaks';s.textContent='.hero:before,.hero-art{display:none!important}#settingsBtn{font-size:0!important}#settingsBtn:after{content:"עריכה";font-size:13px!important;font-weight:700}.task-delete-btn{border:1px solid #efc7cb;background:#fff3f4;color:#a6323f;border-radius:8px;padding:7px 10px;font-weight:800;cursor:pointer}.task-delete-btn:hover{background:#ffe7ea}.task-comments-toggle{border:0;background:#eef5fa;color:#315a7e;border-radius:8px;padding:7px 10px;font-weight:800;cursor:pointer;margin-top:8px}';document.head.appendChild(s);const p=document.getElementById('pin');if(p){p.type='password';p.removeAttribute('inputmode');p.maxLength=64;p.autocomplete='current-password';p.placeholder='סיסמת כניסה'}}
function installProductEditPositioning(){if(window.__clinicProductEditPositioning)return;window.__clinicProductEditPositioning=true;const originalOpen=window.openProduct,originalClose=window.closeProduct;if(typeof originalOpen!=='function'||typeof originalClose!=='function')return;let trigger=null;const style=document.createElement('style');style.id='productEditPositioning';style.textContent='#productForm.product-form-floating{position:fixed!important;z-index:120!important;margin:0!important;width:min(640px,calc(100vw - 20px))!important;max-height:calc(100vh - 20px)!important;overflow:auto!important;box-shadow:0 18px 50px rgba(20,45,70,.22)!important}';document.head.appendChild(style);document.addEventListener('click',e=>{const b=e.target.closest?.('.editbtn');if(b)trigger=b},true);function clearFloating(){const form=document.getElementById('productForm');if(!form)return;form.classList.remove('product-form-floating');form.style.removeProperty('top');form.style.removeProperty('left');form.style.removeProperty('visibility')}function place(form,card){if(!form||!card)return;const pad=10,gap=8,vw=document.documentElement.clientWidth,vh=window.innerHeight,cr=card.getBoundingClientRect();form.style.top=pad+'px';form.style.left=pad+'px';const fr=form.getBoundingClientRect();let left=cr.right-fr.width;left=Math.max(pad,Math.min(left,vw-fr.width-pad));let top=cr.bottom+gap;if(top+fr.height>vh-pad)top=Math.max(pad,cr.top-fr.height-gap);form.style.left=Math.round(left)+'px';form.style.top=Math.round(top)+'px'}window.openProduct=function(id){if(!id){trigger=null;clearFloating();return originalOpen.apply(this,arguments)}const form=document.getElementById('productForm'),card=trigger?.closest?.('.product');if(!form||!card)return originalOpen.apply(this,arguments);form.classList.add('product-form-floating');form.style.visibility='hidden';const nativeScroll=form.scrollIntoView;form.scrollIntoView=()=>{};let result;try{result=originalOpen.apply(this,arguments)}finally{form.scrollIntoView=nativeScroll}requestAnimationFrame(()=>{place(form,card);form.style.visibility='visible'});return result};window.closeProduct=function(){const result=originalClose.apply(this,arguments);clearFloating();trigger=null;return result};window.addEventListener('resize',()=>{const form=document.getElementById('productForm'),card=trigger?.closest?.('.product');if(form&&card&&!form.classList.contains('hidden')&&form.classList.contains('product-form-floating'))place(form,card)})}
function inject(){const app=document.getElementById('app');if(!app||document.getElementById('staffRail'))return;const rail=document.createElement('div');rail.id='staffRail';rail.className='staff-rail';rail.innerHTML=`<button class="staff-rail-btn doctors-tab" title="תזכורות והודעות לרופאים" aria-label="תזכורות והודעות לרופאים" onclick="openStaffTasks('doctors')"><span id="doctorCount" class="staff-count">0</span></button><button class="staff-rail-btn assistants-tab" title="תזכורות והודעות לאסיסטנטיות" aria-label="תזכורות והודעות לאסיסטנטיות" onclick="openStaffTasks('assistants')"><span id="assistantCount" class="staff-count">0</span></button>`;app.appendChild(rail);const overlay=document.createElement('div');overlay.id='taskOverlay';overlay.className='task-overlay';overlay.onclick=closeStaffTasks;app.appendChild(overlay);const drawer=document.createElement('aside');drawer.id='taskDrawer';drawer.className='task-drawer';drawer.innerHTML=`<div class="task-head"><div><h2 id="taskTitle">הודעות ומשימות</h2><div id="taskAudienceLabel" class="muted" style="font-size:12px;margin-top:3px"></div></div><button class="task-close-x" onclick="closeStaffTasks()">×</button></div><div class="task-body"><div class="task-new"><label>כותרת</label><input id="newTaskTitle" class="task-title-input" placeholder="למשל: לחזור ללקוח לגבי בדיקות דם"><label style="margin-top:9px">פירוט המשימה / ההודעה</label><textarea id="newTaskBody" placeholder="כתבו כאן את כל הפרטים שצריך לדעת..."></textarea><div class="task-new-grid"><div><label>מי רשם/ה?</label><select id="newTaskAuthor">${options()}</select></div><button class="btn primary" onclick="createStaffTask()">הוספה</button></div></div><div class="task-modes"><button id="taskOpenBtn" class="task-mode active" onclick="setTaskView('open')">פתוחות</button><button id="taskArchiveBtn" class="task-mode" onclick="setTaskView('closed')">ארכיון משימות</button></div><div id="taskList"></div></div>`;app.appendChild(drawer)}
function setCounts(c){if(!c)return;const dc=document.getElementById('doctorCount'),ac=document.getElementById('assistantCount');if(dc)dc.textContent=String(c.doctors||0);if(ac)ac.textContent=String(c.assistants||0)}
async function ensureList(status){status=status==='closed'?'closed':'open';if(loaded[status])return taskLists[status];try{const all=window.ClinicData?await ClinicData.tasks(status):(await taskApi({action:'list',status,include_comments:false})).items||[];taskLists[status]=all||[];loaded[status]=true;return taskLists[status]}catch(e){if(String(e.message).includes('unauthorized'))showLogin('ההתחברות פגה — התחברי מחדש');throw e}}
function currentItems(){return (taskLists[taskView]||[]).filter(t=>t.audience===currentAudience&&!String(t.body||'').startsWith('[[DAILY]]'))}
window.openStaffTasks=async aud=>{currentAudience=aud;taskView='open';const drawer=document.getElementById('taskDrawer');drawer.classList.remove('doctors-view','assistants-view');drawer.classList.add(aud==='doctors'?'doctors-view':'assistants-view');document.getElementById('taskTitle').textContent=aud==='doctors'?'תזכורות והודעות לרופאים':'תזכורות והודעות לאסיסטנטיות';document.getElementById('taskAudienceLabel').textContent='מערכת פנימית לצוות — כל שינוי נשמר עם תאריך ושעה';drawer.classList.add('open');document.getElementById('taskOverlay').classList.add('open');document.getElementById('taskOpenBtn')?.classList.add('active');document.getElementById('taskArchiveBtn')?.classList.remove('active');const box=document.getElementById('taskList');if(box)box.innerHTML='<div class="task-empty">טוענת…</div>';try{await ensureList('open');renderTaskList()}catch(e){if(box)box.innerHTML=`<div class="task-empty">לא הצלחתי לטעון משימות: ${escT(e.message)}</div>`}};
window.closeStaffTasks=()=>{document.getElementById('taskDrawer')?.classList.remove('open');document.getElementById('taskOverlay')?.classList.remove('open')};
window.setTaskView=async v=>{taskView=v==='closed'?'closed':'open';document.getElementById('taskOpenBtn')?.classList.toggle('active',taskView==='open');document.getElementById('taskArchiveBtn')?.classList.toggle('active',taskView==='closed');const box=document.getElementById('taskList');if(!loaded[taskView]&&box)box.innerHTML='<div class="task-empty">טוענת…</div>';try{await ensureList(taskView);renderTaskList()}catch(e){if(box)box.innerHTML=`<div class="task-empty">לא הצלחתי לטעון: ${escT(e.message)}</div>`}};
function commentBlock(t){const d=details.get(Number(t.id));if(!d)return `<button class="task-comments-toggle" onclick="loadTaskComments(${t.id})">הצגת הערות ועדכונים</button>`;const comments=(d.comments||[]).map(c=>`<div class="comment"><div class="comment-line"><b>${escT(c.author)}</b> — ${escT(c.body)}</div><div class="comment-time">${fmt(c.created_at)}</div></div>`).join('');if(t.status==='closed')return comments?`<div class="task-comments">${comments}</div>`:'<div class="muted" style="font-size:11px">אין הערות</div>';return `<div class="task-comments">${comments||'<div class="muted" style="font-size:11px">אין הערות נוספות</div>'}<div class="comment-form"><label>הוספת הערה / עדכון</label><div class="comment-form-grid"><select id="commentAuthor${t.id}">${options()}</select><textarea id="commentBody${t.id}" placeholder="למשל: לא הצלחתי, צריך לחזור לזה מחר"></textarea><button class="small-action" onclick="addTaskComment(${t.id})">הוסף</button></div></div></div>`}
function taskCard(t){const p=unpackTask(t.body);const deleteBtn=`<button class="task-delete-btn" onclick="deleteStaffTask(${t.id})">מחיקה לצמיתות</button>`;const archive=t.status==='closed'?`<div class="task-footer"><div style="flex:1"><div class="archive-note">נסגרה ${t.closed_at?fmt(t.closed_at):''}${t.closed_by?` על ידי ${escT(t.closed_by)}`:''}</div></div><button class="reopen-btn" onclick="reopenStaffTask(${t.id})">החזרה לפתוחות</button>${deleteBtn}</div>`:`<div class="task-footer"><div class="close-row"><select id="closeAuthor${t.id}">${options()}</select><button class="btn" onclick="closeStaffTask(${t.id})">סגירת משימה והעברה לארכיון</button></div>${deleteBtn}</div>`;return `<article class="task-card"><div class="task-main"><div class="task-card-title">${escT(p.title)}</div><div class="task-text">${escT(p.body)}</div><div class="task-meta"><span><b>${escT(t.author)}</b></span><span>${fmt(t.created_at)}</span></div></div>${commentBlock(t)}${archive}</article>`}
function renderTaskList(){const box=document.getElementById('taskList');if(!box)return;const arr=currentItems();box.innerHTML=arr.length?arr.map(taskCard).join(''):`<div class="task-empty">${taskView==='open'?'אין כרגע משימות פתוחות':'הארכיון עדיין ריק'}</div>`}
window.loadTaskComments=async id=>{try{const item=window.ClinicData?await ClinicData.task(id):(await taskApi({action:'get',id})).item;details.set(Number(id),item||{comments:[]});renderTaskList()}catch(e){alert('לא הצלחתי לטעון הערות: '+e.message)}};
function putItem(item){if(!item)return;for(const s of ['open','closed'])taskLists[s]=taskLists[s].filter(x=>String(x.id)!==String(item.id));if(loaded[item.status])taskLists[item.status].unshift(item);ClinicData?.localTask?.(item);renderTaskList()}
window.createStaffTask=async()=>{const title=document.getElementById('newTaskTitle').value.trim(),body=document.getElementById('newTaskBody').value.trim(),author=document.getElementById('newTaskAuthor').value;if(!title)return alert('צריך להוסיף כותרת למשימה');if(!body)return alert('צריך לכתוב את פרטי המשימה');if(!author)return alert('חייבים לבחור מי רשם/ה את ההודעה');try{const j=await taskApi({action:'create',item:{audience:currentAudience,author,body:packTask(title,body)}});document.getElementById('newTaskTitle').value='';document.getElementById('newTaskBody').value='';document.getElementById('newTaskAuthor').value='';loaded.open=true;putItem(j.item)}catch(e){alert('לא הצלחתי להוסיף: '+e.message)}};
window.addTaskComment=async id=>{const body=document.getElementById('commentBody'+id)?.value.trim(),author=document.getElementById('commentAuthor'+id)?.value;if(!body)return alert('צריך לכתוב הערה');if(!author)return alert('חייבים לבחור מי הוסיף/ה את ההערה');try{const j=await taskApi({action:'comment',task_id:id,author,body});const d=details.get(Number(id))||{comments:[]};d.comments=[...(d.comments||[]),j.item];details.set(Number(id),d);renderTaskList()}catch(e){alert('לא הצלחתי להוסיף הערה: '+e.message)}};
window.closeStaffTask=async id=>{const closed_by=document.getElementById('closeAuthor'+id)?.value;if(!closed_by)return alert('חייבים לבחור מי סוגר/ת את המשימה');if(!confirm('לסגור את המשימה ולהעביר אותה לארכיון?'))return;try{const j=await taskApi({action:'close',id,closed_by});putItem(j.item)}catch(e){alert('לא הצלחתי לסגור: '+e.message)}};
window.reopenStaffTask=async id=>{try{const j=await taskApi({action:'reopen',id});taskView='open';putItem(j.item);document.getElementById('taskOpenBtn')?.classList.add('active');document.getElementById('taskArchiveBtn')?.classList.remove('active')}catch(e){alert('לא הצלחתי להחזיר את המשימה: '+e.message)}};
window.deleteStaffTask=async id=>{const t=[...taskLists.open,...taskLists.closed].find(x=>x.id===id),p=t?unpackTask(t.body):null;if(!confirm(`למחוק לצמיתות את ההודעה${p?.title?' „'+p.title+'”':''}?\n\nהמחיקה תמחק גם את כל ההערות שלה ולא ניתן לשחזר אותה.`))return;try{await taskApi({action:'delete',id});taskLists.open=taskLists.open.filter(x=>x.id!==id);taskLists.closed=taskLists.closed.filter(x=>x.id!==id);details.delete(Number(id));ClinicData?.removeTask?.(id);renderTaskList()}catch(e){alert('לא הצלחתי למחוק: '+e.message)}};
function loadDailyBoard(){if(!document.querySelector('link[href^="daily-board.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='daily-board.css?v=2';document.head.appendChild(l)}if(!document.querySelector('script[src^="daily-board.js"]')){const s=document.createElement('script');s.src='daily-board.js?v=3';document.body.appendChild(s)}}
function startExtras(){if(extrasStarted)return;extrasStarted=true;inject();setCounts(ClinicData?.getTaskCounts?.());loadDailyBoard()}
function boot(){applyUiTweaks();installProductEditPositioning();if(!token())return;startExtras()}
if(window.ClinicData){ClinicData.on('task-counts',setCounts);ClinicData.on('tasks:open',x=>{taskLists.open=x||[];loaded.open=true;if(taskView==='open')renderTaskList()});ClinicData.on('tasks:closed',x=>{taskLists.closed=x||[];loaded.closed=true;if(taskView==='closed')renderTaskList()});ClinicData.on('task-comments-stale',()=>details.clear())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();