(()=>{
const TASK_API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-tasks';
const STAFF=['ד״ר לזר ג׳רסי','ד״ר ג׳מיל טנוס','ד״ר הדס לוי','קים','רננה','אמילי','זהר','רוני','אביטל','דורין'];
let staffTasks=[],currentAudience='doctors',taskView='open';
const escT=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>new Date(d).toLocaleString('he-IL',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
const options=()=>`<option value="" selected disabled>בחרו מי רשם/ה</option>`+STAFF.map(n=>`<option value="${escT(n)}">${escT(n)}</option>`).join('');
const packTask=(title,body)=>`[[TITLE]]${title}\n[[BODY]]${body}`;
function unpackTask(raw){const s=String(raw||'');const m=s.match(/^\[\[TITLE\]\]([\s\S]*?)\n\[\[BODY\]\]([\s\S]*)$/);return m?{title:m[1].trim(),body:m[2].trim()}:{title:'ללא כותרת',body:s}}
async function taskApi(body){const r=await fetch(TASK_API,{method:'POST',headers:{'content-type':'application/json','x-clinic-pin':'1016'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function inject(){const app=document.getElementById('app');if(!app||document.getElementById('staffRail'))return;
 const rail=document.createElement('div');rail.id='staffRail';rail.className='staff-rail';rail.innerHTML=`<button class="staff-rail-btn doctors-tab" title="תזכורות והודעות לרופאים" aria-label="תזכורות והודעות לרופאים" onclick="openStaffTasks('doctors')"><span id="doctorCount" class="staff-count">0</span></button><button class="staff-rail-btn assistants-tab" title="תזכורות והודעות לאסיסטנטיות" aria-label="תזכורות והודעות לאסיסטנטיות" onclick="openStaffTasks('assistants')"><span id="assistantCount" class="staff-count">0</span></button>`;app.appendChild(rail);
 const overlay=document.createElement('div');overlay.id='taskOverlay';overlay.className='task-overlay';overlay.onclick=closeStaffTasks;app.appendChild(overlay);
 const drawer=document.createElement('aside');drawer.id='taskDrawer';drawer.className='task-drawer';drawer.innerHTML=`<div class="task-head"><div><h2 id="taskTitle">הודעות ומשימות</h2><div id="taskAudienceLabel" class="muted" style="font-size:12px;margin-top:3px"></div></div><button class="task-close-x" onclick="closeStaffTasks()">×</button></div><div class="task-body"><div class="task-new"><label>כותרת</label><input id="newTaskTitle" class="task-title-input" placeholder="למשל: לחזור ללקוח לגבי בדיקות דם"><label style="margin-top:9px">פירוט המשימה / ההודעה</label><textarea id="newTaskBody" placeholder="כתבו כאן את כל הפרטים שצריך לדעת..."></textarea><div class="task-new-grid"><div><label>מי רשם/ה?</label><select id="newTaskAuthor">${options()}</select></div><button class="btn primary" onclick="createStaffTask()">הוספה</button></div></div><div class="task-modes"><button id="taskOpenBtn" class="task-mode active" onclick="setTaskView('open')">פתוחות</button><button id="taskArchiveBtn" class="task-mode" onclick="setTaskView('closed')">ארכיון משימות</button></div><div id="taskList"></div></div>`;app.appendChild(drawer);
}
function updateCounts(){const d=staffTasks.filter(t=>t.audience==='doctors'&&t.status==='open').length,a=staffTasks.filter(t=>t.audience==='assistants'&&t.status==='open').length;const dc=document.getElementById('doctorCount'),ac=document.getElementById('assistantCount');if(dc)dc.textContent=d;if(ac)ac.textContent=a}
async function loadTasks(){try{const j=await taskApi({action:'list'});staffTasks=j.items||[];updateCounts();renderTaskList()}catch(e){const box=document.getElementById('taskList');if(box)box.innerHTML=`<div class="task-empty">לא הצלחתי לטעון משימות: ${escT(e.message)}</div>`}}
window.openStaffTasks=async aud=>{currentAudience=aud;taskView='open';document.getElementById('taskTitle').textContent=aud==='doctors'?'תזכורות והודעות לרופאים':'תזכורות והודעות לאסיסטנטיות';document.getElementById('taskAudienceLabel').textContent='מערכת פנימית לצוות — כל שינוי נשמר עם תאריך ושעה';document.getElementById('taskDrawer').classList.add('open');document.getElementById('taskOverlay').classList.add('open');setTaskView('open');await loadTasks()};
window.closeStaffTasks=()=>{document.getElementById('taskDrawer')?.classList.remove('open');document.getElementById('taskOverlay')?.classList.remove('open')};
window.setTaskView=v=>{taskView=v;document.getElementById('taskOpenBtn')?.classList.toggle('active',v==='open');document.getElementById('taskArchiveBtn')?.classList.toggle('active',v==='closed');renderTaskList()};
function taskCard(t){const p=unpackTask(t.body);const comments=(t.comments||[]).map(c=>`<div class="comment"><div class="comment-line"><b>${escT(c.author)}</b> — ${escT(c.body)}</div><div class="comment-time">${fmt(c.created_at)}</div></div>`).join('');
 const archive=t.status==='closed'?`<div class="task-footer"><div style="flex:1"><div class="archive-note">נסגרה ${t.closed_at?fmt(t.closed_at):''}${t.closed_by?` על ידי ${escT(t.closed_by)}`:''}</div></div><button class="reopen-btn" onclick="reopenStaffTask(${t.id})">החזרה לפתוחות</button></div>`:`<div class="task-comments">${comments||'<div class="muted" style="font-size:11px">אין הערות נוספות</div>'}<div class="comment-form"><label>הוספת הערה / עדכון</label><div class="comment-form-grid"><select id="commentAuthor${t.id}">${options()}</select><textarea id="commentBody${t.id}" placeholder="למשל: לא הצלחתי, צריך לחזור לזה מחר"></textarea><button class="small-action" onclick="addTaskComment(${t.id})">הוסף</button></div></div></div><div class="task-footer"><div class="close-row"><select id="closeAuthor${t.id}">${options()}</select><button class="btn" onclick="closeStaffTask(${t.id})">סגירת משימה והעברה לארכיון</button></div></div>`;
 const closedComments=t.status==='closed'&&comments?`<div class="task-comments">${comments}</div>`:'';
 return `<article class="task-card"><div class="task-main"><div class="task-card-title">${escT(p.title)}</div><div class="task-text">${escT(p.body)}</div><div class="task-meta"><span><b>${escT(t.author)}</b></span><span>${fmt(t.created_at)}</span></div></div>${t.status==='closed'?closedComments:''}${archive}</article>`}
function renderTaskList(){const box=document.getElementById('taskList');if(!box)return;const arr=staffTasks.filter(t=>t.audience===currentAudience&&t.status===taskView);box.innerHTML=arr.length?arr.map(taskCard).join(''):`<div class="task-empty">${taskView==='open'?'אין כרגע משימות פתוחות':'הארכיון עדיין ריק'}</div>`}
window.createStaffTask=async()=>{const title=document.getElementById('newTaskTitle').value.trim(),body=document.getElementById('newTaskBody').value.trim(),author=document.getElementById('newTaskAuthor').value;if(!title)return alert('צריך להוסיף כותרת למשימה');if(!body)return alert('צריך לכתוב את פרטי המשימה');if(!author)return alert('חייבים לבחור מי רשם/ה את ההודעה');try{await taskApi({action:'create',item:{audience:currentAudience,author,body:packTask(title,body)}});document.getElementById('newTaskTitle').value='';document.getElementById('newTaskBody').value='';document.getElementById('newTaskAuthor').value='';await loadTasks()}catch(e){alert('לא הצלחתי להוסיף: '+e.message)}};
window.addTaskComment=async id=>{const body=document.getElementById('commentBody'+id).value.trim(),author=document.getElementById('commentAuthor'+id).value;if(!body)return alert('צריך לכתוב הערה');if(!author)return alert('חייבים לבחור מי הוסיף/ה את ההערה');try{await taskApi({action:'comment',task_id:id,author,body});await loadTasks()}catch(e){alert('לא הצלחתי להוסיף הערה: '+e.message)}};
window.closeStaffTask=async id=>{const closed_by=document.getElementById('closeAuthor'+id).value;if(!closed_by)return alert('חייבים לבחור מי סוגר/ת את המשימה');if(!confirm('לסגור את המשימה ולהעביר אותה לארכיון?'))return;try{await taskApi({action:'close',id,closed_by});await loadTasks()}catch(e){alert('לא הצלחתי לסגור: '+e.message)}};
window.reopenStaffTask=async id=>{try{await taskApi({action:'reopen',id});taskView='open';await loadTasks();setTaskView('open')}catch(e){alert('לא הצלחתי להחזיר את המשימה: '+e.message)}};
function boot(){inject();loadTasks()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();