(()=>{
const OPS_API='https://bhvkhxmexyhsjhwjsytp.supabase.co/functions/v1/clinic-ops';
const SUPPLIERS=[
 {id:'olga',title:'אולגה – הזמנות מהסוכנת',contact:'אולגה',phone:'0503330347',note:'עבודה נוחה עם הסוכנת שלהם; מתקשרים בעיקר בוואטסאפ.',products:['אוריזון – טיפות אוזניים','תילוע דולפאק','שטיפת אוזניים נוטרלי קלין','פרופייבר','פרוקולין','סינביוטיק','פלאק אוף','פרוקוקס','קלמגין','אמוקסי LA','פרופאלין','דנטהקס']},
 {id:'petvet',title:'פט וט ביומד',contact:'אילן',phone:'0524271316',note:'מוצרים שמופיעים בדף ההזמנות.',products:['קטמין','שמפואים מסדרת דרמטורט','איזיפיל']},
 {id:'medimarket',title:'מדי-מרקט',contact:'ליהי',phone:'0502900021',note:'מזמינים דרכה רק שבבים. לפי הדף: לאמילי בלבד.',products:['שבבים']},
 {id:'amiti',title:'אמיתי',contact:'יובל גת',phone:'0525333066',note:'כל מוצרי ה״חנות״ ומוצרים משלימים.',products:['חטיפים','רצועות','מסרקים','קולרים','אבקה לעצירת דימום מהציפורניים','תוסף תזונה קלציום','מי פה','משחה לכדורי פרווה בחתולים']}
];
let orders=[],view='open';
const token=()=>localStorage.getItem('clinic_session_token')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const supplier=id=>SUPPLIERS.find(x=>x.id===id)||SUPPLIERS[0];
async function call(body){const r=await fetch(OPS_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token()},body:JSON.stringify(body),cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'שגיאה');return j}
function addCss(){if(document.querySelector('link[data-supplier-orders]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='supplier-orders.css?v=1';l.dataset.supplierOrders='1';document.head.appendChild(l)}
function addSideNav(){const nav=document.querySelector('#clinicSidebar nav');if(!nav||nav.querySelector('[data-view="supplierOrders"]'))return false;const b=document.createElement('button');b.className='clinic-nav-btn';b.dataset.view='supplierOrders';b.setAttribute('onclick',"clinicNavigate('supplierOrders')");b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h12v10H3z"/><path d="M15 10h3l3 3v4h-6z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></svg><span>הזמנות ספקים</span>';const food=nav.querySelector('[data-view="foodbags"]');const inv=nav.querySelector('[data-view="inventory"]');(food||inv)?.insertAdjacentElement('afterend',b)||nav.appendChild(b);return true}
function supplierCards(){return SUPPLIERS.map(s=>`<article class="supplier-card"><h3>${esc(s.title)}</h3><p class="supplier-note">${esc(s.note)}</p><a class="supplier-phone" href="tel:${s.phone}">☎ ${esc(s.contact)} · ${esc(s.phone)}</a><div class="supplier-products">${s.products.map(p=>`<span>${esc(p)}</span>`).join('')}</div></article>`).join('')}
function setupPanel(){let p=document.getElementById('supplierOrders');if(!p){p=document.createElement('section');p.id='supplierOrders';p.className='panel hidden';document.getElementById('app')?.appendChild(p)}if(!p||p.dataset.ready==='1')return !!p;p.dataset.ready='1';p.innerHTML=`<div class="supplier-page-head"><div><h2>הזמנות ספקים</h2><p>אנשי קשר, מה מזמינים מכל ספק ומעקב אחר הזמנות פתוחות.</p></div></div><div class="supplier-cards">${supplierCards()}</div><div class="supplier-order-box"><h3>הוספת פריט להזמנה</h3><div class="supplier-form-grid"><div class="supplier-field"><label>ספק</label><select id="supplierPick" onchange="supplierRefreshProducts()">${SUPPLIERS.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join('')}</select></div><div class="supplier-field wide"><label>פריט</label><input id="supplierItem" list="supplierProductList" placeholder="שם המוצר / התרופה"><datalist id="supplierProductList"></datalist></div><div class="supplier-field"><label>כמות</label><input id="supplierQty" type="number" min="1" value="1"></div><div class="supplier-field"><label>לקוח / מטופל</label><input id="supplierClient" placeholder="אופציונלי"></div><div class="supplier-field wide"><label>הערה</label><input id="supplierNote" placeholder="מינון, דחיפות, פרטים נוספים..."></div><button class="btn primary supplier-add" onclick="supplierAddOrder()">הוספה להזמנה</button></div><div class="supplier-paper-note">המידע על הספקים והמוצרים הוזן לפי דף ההוראות שצולם במרפאה. אפשר להוסיף גם פריטים שלא מופיעים ברשימה.</div><div class="supplier-order-tabs"><button id="supplierOpenTab" class="supplier-order-tab active" onclick="supplierSetView('open')">פתוחות</button><button id="supplierReceivedTab" class="supplier-order-tab" onclick="supplierSetView('received')">התקבלו</button></div><div id="supplierOrdersList" class="supplier-orders-list"></div></div>`;supplierRefreshProducts();return true}
window.supplierRefreshProducts=()=>{const s=supplier(document.getElementById('supplierPick')?.value);const dl=document.getElementById('supplierProductList');if(dl)dl.innerHTML=s.products.map(p=>`<option value="${esc(p)}"></option>`).join('')};
async function load(){if(!token())return;const j=await call({action:'list'});orders=Array.isArray(j.items?.orders)?j.items.orders:[];render()}
async function save(){await call({action:'save',key:'orders',data:orders});render()}
function normalize(x,i){return {...x,_i:i,status:x.status||(x.received?'received':x.done?'ordered':'pending'),qty:Number(x.qty||1)}}
function orderHtml(x){const s=SUPPLIERS.find(z=>z.id===x.supplier_id);const title=s?.title||x.supplier||'ספק לא צוין';const status=x.status==='ordered'?'הוזמן':x.status==='received'?'התקבל':'ממתין להזמנה';const cls=x.status==='ordered'?'ordered':x.status==='received'?'received':'';return `<div class="supplier-order-row ${cls}"><div><span class="supplier-badge">${esc(title)}</span></div><div><b>${esc(x.name)}</b>${x.client?`<small>לקוח/מטופל: ${esc(x.client)}</small>`:''}</div><div><b>× ${x.qty}</b></div><div><span class="supplier-badge">${status}</span></div><div>${x.note?esc(x.note):'<span class="muted">ללא הערה</span>'}</div><div class="supplier-order-actions">${x.status==='pending'?`<button onclick="supplierMarkOrdered(${x._i})">סמני שהוזמן</button>`:''}${x.status!=='received'?`<button onclick="supplierMarkReceived(${x._i})">סמני שהתקבל</button>`:`<button onclick="supplierReopen(${x._i})">החזרה לפתוחות</button>`}<button class="danger" onclick="supplierDelete(${x._i})">מחיקה</button></div></div>`}
function render(){const box=document.getElementById('supplierOrdersList');if(!box)return;const arr=orders.map(normalize).filter(x=>view==='received'?x.status==='received':x.status!=='received');box.innerHTML=arr.length?arr.map(orderHtml).join(''):`<div class="supplier-empty">${view==='received'?'אין הזמנות שהתקבלו עדיין.':'אין כרגע הזמנות פתוחות.'}</div>`}
window.supplierSetView=v=>{view=v;document.getElementById('supplierOpenTab')?.classList.toggle('active',v==='open');document.getElementById('supplierReceivedTab')?.classList.toggle('active',v==='received');render()};
window.supplierAddOrder=async()=>{const sid=document.getElementById('supplierPick')?.value||'olga',name=document.getElementById('supplierItem')?.value.trim()||'',qty=Math.max(1,Number(document.getElementById('supplierQty')?.value||1)),client=document.getElementById('supplierClient')?.value.trim()||'',note=document.getElementById('supplierNote')?.value.trim()||'';if(!name)return alert('צריך לכתוב מה מזמינים');const s=supplier(sid);orders.push({supplier_id:sid,supplier:s.title,name,qty,client,note,status:'pending',done:false,created_at:new Date().toISOString()});document.getElementById('supplierItem').value='';document.getElementById('supplierQty').value='1';document.getElementById('supplierClient').value='';document.getElementById('supplierNote').value='';await save()};
window.supplierMarkOrdered=async i=>{if(!orders[i])return;orders[i].status='ordered';orders[i].done=true;orders[i].ordered_at=new Date().toISOString();await save()};
window.supplierMarkReceived=async i=>{if(!orders[i])return;orders[i].status='received';orders[i].done=true;orders[i].received=true;orders[i].received_at=new Date().toISOString();await save()};
window.supplierReopen=async i=>{if(!orders[i])return;orders[i].status='pending';orders[i].done=false;orders[i].received=false;await save()};
window.supplierDelete=async i=>{if(!orders[i]||!confirm('למחוק את ההזמנה מהרשימה?'))return;orders.splice(i,1);await save()};
function wrapNavigate(){if(window.__supplierNavigateWrapped||typeof window.clinicNavigate!=='function')return;window.__supplierNavigateWrapped=true;const orig=window.clinicNavigate;window.clinicNavigate=function(viewName){if(viewName==='supplierOrders'){document.getElementById('clinicHome')?.classList.add('hidden');document.getElementById('clinicOps')?.classList.add('hidden');document.querySelectorAll('#app .panel').forEach(x=>x.classList.add('hidden'));document.getElementById('supplierOrders')?.classList.remove('hidden');document.querySelectorAll('.clinic-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='supplierOrders'));load();window.scrollTo({top:0,behavior:'smooth'});return}return orig.apply(this,arguments)}}
function boot(){addCss();setupPanel();addSideNav();wrapNavigate();return !!document.getElementById('supplierOrders')&&!!document.querySelector('[data-view="supplierOrders"]')}
let tries=0;const timer=setInterval(()=>{tries++;if(boot()||tries>70)clearInterval(timer)},200);if(document.readyState!=='loading')boot();else document.addEventListener('DOMContentLoaded',boot);
})();